"""

        python binding of zv robot sdk
        -----------------------
    
"""
from __future__ import annotations
import collections.abc
import typing
import typing_extensions
__all__: list[str] = ['AllJointCmd_', 'AllJointState_', 'ChannelFactory', 'ChannelPublisher_AllJointCmd_', 'ChannelPublisher_String_', 'ChannelSubscriber_AllJointState_', 'ChannelSubscriber_String_', 'JointCmd_', 'JointState_', 'RemoteControlChange_', 'RemoteControlMotion_', 'String_', 'Time_']
class AllJointCmd_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: AllJointCmd_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt, index_: typing.SupportsInt, cmd_type_: typing.SupportsInt, joint_cmds_: collections.abc.Sequence[JointCmd_]) -> None:
        ...
    def __ne__(self, arg0: AllJointCmd_) -> bool:
        ...
    @property
    def cmd_type_(self) -> int:
        ...
    @cmd_type_.setter
    def cmd_type_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def index_(self) -> int:
        ...
    @index_.setter
    def index_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_cmds_(self) -> list[JointCmd_]:
        ...
    @joint_cmds_.setter
    def joint_cmds_(self, arg1: collections.abc.Sequence[JointCmd_]) -> None:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
class AllJointState_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: AllJointState_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt, index_: typing.SupportsInt, joint_states_: collections.abc.Sequence[JointState_]) -> None:
        ...
    def __ne__(self, arg0: AllJointState_) -> bool:
        ...
    @property
    def index_(self) -> int:
        ...
    @index_.setter
    def index_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_states_(self) -> list[JointState_]:
        ...
    @joint_states_.setter
    def joint_states_(self, arg1: collections.abc.Sequence[JointState_]) -> None:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
class ChannelFactory:
    @staticmethod
    def Instance() -> ChannelFactory:
        """
                            Get the singleton instance of the channel factory.
                            Note: The returned instance is managed internally and should not be deleted or modified.
        """
    @typing.overload
    def Init(self, domain_id: typing.SupportsInt, network_interface: str = '') -> None:
        ...
    @typing.overload
    def Init(self, json_config_str: str) -> None:
        """
        config in json string
        """
    def Release(self) -> None:
        ...
class ChannelPublisher_AllJointCmd_:
    def CloseChannel(self) -> None:
        ...
    def GetChannelName(self) -> str:
        ...
    def InitChannel(self) -> None:
        ...
    def Write(self, msg: AllJointCmd_, wait_microsec: typing.SupportsInt = 0) -> None:
        ...
    def __init__(self, channel_name: str) -> None:
        ...
class ChannelPublisher_String_:
    def CloseChannel(self) -> None:
        ...
    def GetChannelName(self) -> str:
        ...
    def InitChannel(self) -> None:
        ...
    def Write(self, msg: String_, wait_microsec: typing.SupportsInt = 0) -> None:
        ...
    def __init__(self, channel_name: str) -> None:
        ...
class ChannelSubscriber_AllJointState_:
    def CloseChannel(self) -> None:
        ...
    def GetChannelName(self) -> str:
        ...
    @typing.overload
    def InitChannel(self, handler: collections.abc.Callable[[typing_extensions.CapsuleType], None], queue_len: typing.SupportsInt = 0) -> None:
        ...
    @typing.overload
    def InitChannel(self) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str, handler: collections.abc.Callable[[typing_extensions.CapsuleType], None], queue_len: typing.SupportsInt = 0) -> None:
        ...
class ChannelSubscriber_String_:
    def CloseChannel(self) -> None:
        ...
    def GetChannelName(self) -> str:
        ...
    @typing.overload
    def InitChannel(self, handler: collections.abc.Callable[[typing_extensions.CapsuleType], None], queue_len: typing.SupportsInt = 0) -> None:
        ...
    @typing.overload
    def InitChannel(self) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str, handler: collections.abc.Callable[[typing_extensions.CapsuleType], None], queue_len: typing.SupportsInt = 0) -> None:
        ...
class JointCmd_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: JointCmd_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, joint_pos_: typing.SupportsFloat, joint_vel_: typing.SupportsFloat, joint_torque_: typing.SupportsFloat, kp_: typing.SupportsFloat, kd_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: JointCmd_) -> bool:
        ...
    @property
    def joint_pos_(self) -> float:
        ...
    @joint_pos_.setter
    def joint_pos_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def joint_torque_(self) -> float:
        ...
    @joint_torque_.setter
    def joint_torque_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def joint_vel_(self) -> float:
        ...
    @joint_vel_.setter
    def joint_vel_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def kd_(self) -> float:
        ...
    @kd_.setter
    def kd_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def kp_(self) -> float:
        ...
    @kp_.setter
    def kp_(self, arg1: typing.SupportsFloat) -> None:
        ...
class JointState_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: JointState_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, joint_pos_: typing.SupportsFloat, joint_vel_: typing.SupportsFloat, joint_torque_: typing.SupportsFloat, temp_motor_: typing.SupportsInt, temp_mos_: typing.SupportsInt, error_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: JointState_) -> bool:
        ...
    @property
    def error_(self) -> int:
        ...
    @error_.setter
    def error_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_pos_(self) -> float:
        ...
    @joint_pos_.setter
    def joint_pos_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def joint_torque_(self) -> float:
        ...
    @joint_torque_.setter
    def joint_torque_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def joint_vel_(self) -> float:
        ...
    @joint_vel_.setter
    def joint_vel_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def temp_mos_(self) -> int:
        ...
    @temp_mos_.setter
    def temp_mos_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def temp_motor_(self) -> int:
        ...
    @temp_motor_.setter
    def temp_motor_(self, arg1: typing.SupportsInt) -> None:
        ...
class RemoteControlChange_:
    __hash__: typing.ClassVar[None] = None
    key_: str
    val_: str
    def __eq__(self, arg0: RemoteControlChange_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, key_: str, val_: str) -> None:
        ...
    def __ne__(self, arg0: RemoteControlChange_) -> bool:
        ...
class RemoteControlMotion_:
    __hash__: typing.ClassVar[None] = None
    is_continous_: bool
    def __eq__(self, arg0: RemoteControlMotion_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, vx_: typing.SupportsFloat, vy_: typing.SupportsFloat, vyaw_: typing.SupportsFloat, gait_step_: typing.SupportsFloat, is_continous_: bool) -> None:
        ...
    def __ne__(self, arg0: RemoteControlMotion_) -> bool:
        ...
    @property
    def gait_step_(self) -> float:
        ...
    @gait_step_.setter
    def gait_step_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def vx_(self) -> float:
        ...
    @vx_.setter
    def vx_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def vy_(self) -> float:
        ...
    @vy_.setter
    def vy_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def vyaw_(self) -> float:
        ...
    @vyaw_.setter
    def vyaw_(self, arg1: typing.SupportsFloat) -> None:
        ...
class String_:
    __hash__: typing.ClassVar[None] = None
    data_: str
    def __eq__(self, arg0: String_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, data_: str) -> None:
        ...
    def __ne__(self, arg0: String_) -> bool:
        ...
class Time_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Time_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, sec_: typing.SupportsInt, nanosec_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: Time_) -> bool:
        ...
    @property
    def nanosec_(self) -> int:
        ...
    @nanosec_.setter
    def nanosec_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def sec_(self) -> int:
        ...
    @sec_.setter
    def sec_(self, arg1: typing.SupportsInt) -> None:
        ...
__version__: str = '1.0.0'
