/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: AllJointCmd_.idl
  Source: AllJointCmd_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_ALLJOINTCMD__HPP
#define DDSCXX_ALLJOINTCMD__HPP

#include "JointCmd_.hpp"

#include <cstdint>
#include <vector>

namespace robot_msgs
{
namespace msg
{
namespace dds_
{
class AllJointCmd_
{
private:
 int64_t timestamp__ = 0;
 int64_t index__ = 0;
 uint8_t cmd_type__ = 0;
 std::vector<::robot_msgs::msg::dds_::JointCmd_> joint_cmds__;

public:
  AllJointCmd_() = default;

  explicit AllJointCmd_(
    int64_t timestamp_,
    int64_t index_,
    uint8_t cmd_type_,
    const std::vector<::robot_msgs::msg::dds_::JointCmd_>& joint_cmds_) :
    timestamp__(timestamp_),
    index__(index_),
    cmd_type__(cmd_type_),
    joint_cmds__(joint_cmds_) { }

  int64_t timestamp_() const { return this->timestamp__; }
  int64_t& timestamp_() { return this->timestamp__; }
  void timestamp_(int64_t _val_) { this->timestamp__ = _val_; }
  int64_t index_() const { return this->index__; }
  int64_t& index_() { return this->index__; }
  void index_(int64_t _val_) { this->index__ = _val_; }
  uint8_t cmd_type_() const { return this->cmd_type__; }
  uint8_t& cmd_type_() { return this->cmd_type__; }
  void cmd_type_(uint8_t _val_) { this->cmd_type__ = _val_; }
  const std::vector<::robot_msgs::msg::dds_::JointCmd_>& joint_cmds_() const { return this->joint_cmds__; }
  std::vector<::robot_msgs::msg::dds_::JointCmd_>& joint_cmds_() { return this->joint_cmds__; }
  void joint_cmds_(const std::vector<::robot_msgs::msg::dds_::JointCmd_>& _val_) { this->joint_cmds__ = _val_; }
  void joint_cmds_(std::vector<::robot_msgs::msg::dds_::JointCmd_>&& _val_) { this->joint_cmds__ = _val_; }

  bool operator==(const AllJointCmd_& _other) const
  {
    (void) _other;
    return timestamp__ == _other.timestamp__ &&
      index__ == _other.index__ &&
      cmd_type__ == _other.cmd_type__ &&
      joint_cmds__ == _other.joint_cmds__;
  }

  bool operator!=(const AllJointCmd_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::robot_msgs::msg::dds_::AllJointCmd_>::getTypeName()
{
  return "robot_msgs::msg::dds_::AllJointCmd_";
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::AllJointCmd_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::AllJointCmd_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::AllJointCmd_>::type_map_blob_sz() { return 772; }
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::AllJointCmd_>::type_info_blob_sz() { return 148; }
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::AllJointCmd_>::type_map_blob() {
  static const uint8_t blob[] = {
 0xf7,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0xf1,  0x7a,  0xe2,  0x20,  0x58,  0x94,  0xd3,  0x54, 
 0x45,  0xc7,  0x3e,  0x0a,  0x7f,  0x78,  0xab,  0x00,  0x66,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x56,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x05,  0xee,  0x0a,  0x2c,  0x82,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x05,  0x3d,  0x7c,  0x34,  0x1c,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x2d,  0x79,  0x1e,  0xd0,  0x00, 
 0x1e,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf1,  0x01,  0x00,  0x00,  0xf1, 
 0xb6,  0x58,  0x09,  0x48,  0xf4,  0x55,  0xd9,  0x72,  0xbf,  0x77,  0x5f,  0xda,  0x0e,  0x2c,  0xc7,  0x6d, 
 0x2c,  0x03,  0xf1,  0xb6,  0x58,  0x09,  0x48,  0xf4,  0x55,  0xd9,  0x72,  0xbf,  0x77,  0x5f,  0xda,  0x0e, 
 0x2c,  0x00,  0x00,  0x00,  0x63,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x53,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x06,  0x1b,  0x26,  0xf8,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0xfd,  0xf3,  0x1d,  0x75,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x65,  0x3f,  0x72,  0x49,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x27,  0x26,  0x80,  0x3f,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x79,  0xe6,  0xc0,  0x52,  0x00,  0xbe,  0x01,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0xf2,  0xde,  0xfc,  0x27,  0x92,  0x22,  0x5d,  0x53,  0xf5,  0x7a,  0xc8,  0x49, 
 0x68,  0x33,  0xfa,  0x00,  0xc6,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x2c,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00,  0x72,  0x6f,  0x62,  0x6f,  0x74,  0x5f,  0x6d,  0x73, 
 0x67,  0x73,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x41, 
 0x6c,  0x6c,  0x4a,  0x6f,  0x69,  0x6e,  0x74,  0x43,  0x6d,  0x64,  0x5f,  0x00,  0x8e,  0x00,  0x00,  0x00, 
 0x04,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x05,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x74,  0x69,  0x6d,  0x65,  0x73,  0x74,  0x61,  0x6d,  0x70,  0x5f,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x05,  0x00, 
 0x07,  0x00,  0x00,  0x00,  0x69,  0x6e,  0x64,  0x65,  0x78,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x18,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00,  0x0a,  0x00,  0x00,  0x00, 
 0x63,  0x6d,  0x64,  0x5f,  0x74,  0x79,  0x70,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x2e,  0x00,  0x00,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf2,  0x01,  0x00,  0x00,  0xf2,  0x65,  0xfd,  0xed,  0x99, 
 0x34,  0x9d,  0x62,  0x0e,  0x42,  0xe9,  0xbc,  0x06,  0x37,  0x6b,  0x00,  0x00,  0x0c,  0x00,  0x00,  0x00, 
 0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x63,  0x6d,  0x64,  0x73,  0x5f,  0x00,  0x00,  0x00,  0xf2,  0x65, 
 0xfd,  0xed,  0x99,  0x34,  0x9d,  0x62,  0x0e,  0x42,  0xe9,  0xbc,  0x06,  0x37,  0x6b,  0x00,  0x00,  0x00, 
 0xca,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x29,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x21,  0x00,  0x00,  0x00,  0x72,  0x6f,  0x62,  0x6f,  0x74,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a, 
 0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x4a,  0x6f,  0x69,  0x6e,  0x74, 
 0x43,  0x6d,  0x64,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x92,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x70,  0x6f,  0x73,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x19,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x76,  0x65,  0x6c,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x1c,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x00,  0x0e,  0x00,  0x00,  0x00, 
 0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x74,  0x6f,  0x72,  0x71,  0x75,  0x65,  0x5f,  0x00,  0x00,  0x00, 
 0x12,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x6b,  0x70,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x12,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x0a,  0x00,  0x04,  0x00,  0x00,  0x00,  0x6b,  0x64,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x40,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0xf2,  0xde,  0xfc,  0x27,  0x92,  0x22,  0x5d,  0x53, 
 0xf5,  0x7a,  0xc8,  0x49,  0x68,  0x33,  0xfa,  0xf1,  0x7a,  0xe2,  0x20,  0x58,  0x94,  0xd3,  0x54,  0x45, 
 0xc7,  0x3e,  0x0a,  0x7f,  0x78,  0xab,  0xf2,  0x65,  0xfd,  0xed,  0x99,  0x34,  0x9d,  0x62,  0x0e,  0x42, 
 0xe9,  0xbc,  0x06,  0x37,  0x6b,  0xf1,  0xb6,  0x58,  0x09,  0x48,  0xf4,  0x55,  0xd9,  0x72,  0xbf,  0x77, 
 0x5f,  0xda,  0x0e,  0x2c, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::AllJointCmd_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x90,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x40,  0x00,  0x00,  0x00,  0x3c,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x7a,  0xe2,  0x20,  0x58,  0x94,  0xd3,  0x54,  0x45,  0xc7,  0x3e,  0x0a, 
 0x7f,  0x78,  0xab,  0x00,  0x6a,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf1,  0xb6,  0x58,  0x09,  0x48,  0xf4,  0x55,  0xd9, 
 0x72,  0xbf,  0x77,  0x5f,  0xda,  0x0e,  0x2c,  0x00,  0x67,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40, 
 0x40,  0x00,  0x00,  0x00,  0x3c,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf2,  0xde,  0xfc,  0x27, 
 0x92,  0x22,  0x5d,  0x53,  0xf5,  0x7a,  0xc8,  0x49,  0x68,  0x33,  0xfa,  0x00,  0xca,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00, 
 0xf2,  0x65,  0xfd,  0xed,  0x99,  0x34,  0x9d,  0x62,  0x0e,  0x42,  0xe9,  0xbc,  0x06,  0x37,  0x6b,  0x00, 
 0xce,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::robot_msgs::msg::dds_::AllJointCmd_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::robot_msgs::msg::dds_::AllJointCmd_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::robot_msgs::msg::dds_::AllJointCmd_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::robot_msgs::msg::dds_::AllJointCmd_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::robot_msgs::msg::dds_::AllJointCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.timestamp_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.index_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.cmd_type_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_cmds_().size());
      if (!write(streamer, se_1))
        return false;
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!write(streamer, instance.joint_cmds_()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::robot_msgs::msg::dds_::AllJointCmd_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::AllJointCmd_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::robot_msgs::msg::dds_::AllJointCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.timestamp_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.index_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.cmd_type_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_cmds_().size());
      if (!read(streamer, se_1))
        return false;
      instance.joint_cmds_().resize(se_1);
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!read(streamer, instance.joint_cmds_()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::robot_msgs::msg::dds_::AllJointCmd_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::AllJointCmd_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::robot_msgs::msg::dds_::AllJointCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.timestamp_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.index_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.cmd_type_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.joint_cmds_().size());
      if (!move(streamer, se_1))
        return false;
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!move(streamer, instance.joint_cmds_()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::robot_msgs::msg::dds_::AllJointCmd_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::AllJointCmd_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::robot_msgs::msg::dds_::AllJointCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.timestamp_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.index_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.cmd_type_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!max(streamer, instance.joint_cmds_()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::robot_msgs::msg::dds_::AllJointCmd_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::AllJointCmd_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_ALLJOINTCMD__HPP
