/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: ArmControl_.idl
  Source: ArmControl_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_ARMCONTROL__HPP
#define DDSCXX_ARMCONTROL__HPP

#include "ZVHeader_.hpp"

#include <cstdint>
#include <vector>

namespace robot_msgs
{
namespace msg
{
namespace dds_
{
class ArmControl_
{
private:
 ::comm_msgs::msg::dds_::ZVHeader_ header__;
 uint8_t arm__ = 0;
 uint8_t motion_type__ = 0;
 std::vector<float> hand_target__;
 std::vector<float> arm_target__;
 float velocity__ = 0.0f;
 uint8_t change_motion_state__ = 0;

public:
  ArmControl_() = default;

  explicit ArmControl_(
    const ::comm_msgs::msg::dds_::ZVHeader_& header_,
    uint8_t arm_,
    uint8_t motion_type_,
    const std::vector<float>& hand_target_,
    const std::vector<float>& arm_target_,
    float velocity_,
    uint8_t change_motion_state_) :
    header__(header_),
    arm__(arm_),
    motion_type__(motion_type_),
    hand_target__(hand_target_),
    arm_target__(arm_target_),
    velocity__(velocity_),
    change_motion_state__(change_motion_state_) { }

  const ::comm_msgs::msg::dds_::ZVHeader_& header_() const { return this->header__; }
  ::comm_msgs::msg::dds_::ZVHeader_& header_() { return this->header__; }
  void header_(const ::comm_msgs::msg::dds_::ZVHeader_& _val_) { this->header__ = _val_; }
  void header_(::comm_msgs::msg::dds_::ZVHeader_&& _val_) { this->header__ = _val_; }
  uint8_t arm_() const { return this->arm__; }
  uint8_t& arm_() { return this->arm__; }
  void arm_(uint8_t _val_) { this->arm__ = _val_; }
  uint8_t motion_type_() const { return this->motion_type__; }
  uint8_t& motion_type_() { return this->motion_type__; }
  void motion_type_(uint8_t _val_) { this->motion_type__ = _val_; }
  const std::vector<float>& hand_target_() const { return this->hand_target__; }
  std::vector<float>& hand_target_() { return this->hand_target__; }
  void hand_target_(const std::vector<float>& _val_) { this->hand_target__ = _val_; }
  void hand_target_(std::vector<float>&& _val_) { this->hand_target__ = _val_; }
  const std::vector<float>& arm_target_() const { return this->arm_target__; }
  std::vector<float>& arm_target_() { return this->arm_target__; }
  void arm_target_(const std::vector<float>& _val_) { this->arm_target__ = _val_; }
  void arm_target_(std::vector<float>&& _val_) { this->arm_target__ = _val_; }
  float velocity_() const { return this->velocity__; }
  float& velocity_() { return this->velocity__; }
  void velocity_(float _val_) { this->velocity__ = _val_; }
  uint8_t change_motion_state_() const { return this->change_motion_state__; }
  uint8_t& change_motion_state_() { return this->change_motion_state__; }
  void change_motion_state_(uint8_t _val_) { this->change_motion_state__ = _val_; }

  bool operator==(const ArmControl_& _other) const
  {
    (void) _other;
    return header__ == _other.header__ &&
      arm__ == _other.arm__ &&
      motion_type__ == _other.motion_type__ &&
      hand_target__ == _other.hand_target__ &&
      arm_target__ == _other.arm_target__ &&
      velocity__ == _other.velocity__ &&
      change_motion_state__ == _other.change_motion_state__;
  }

  bool operator!=(const ArmControl_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::robot_msgs::msg::dds_::ArmControl_>::getTypeName()
{
  return "robot_msgs::msg::dds_::ArmControl_";
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::ArmControl_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::ArmControl_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::ArmControl_>::type_map_blob_sz() { return 1094; }
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::ArmControl_>::type_info_blob_sz() { return 196; }
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::ArmControl_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x63,  0x01,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0xf1,  0x27,  0x8b,  0xfa,  0x05,  0x95,  0x59,  0x28, 
 0x93,  0x69,  0x93,  0xae,  0x4e,  0x52,  0x9f,  0x00,  0x9b,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x8b,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00, 
 0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0xf1,  0xc6,  0xa1,  0x08,  0xd2,  0xb6, 
 0x72,  0x73,  0x7b,  0xf5,  0x94,  0xd8,  0x5d,  0x84,  0xbf,  0xd8,  0xe7,  0xf6,  0x3d,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0xd9,  0xa7,  0x87,  0x47,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0xdc,  0x71,  0x48,  0xf0,  0x00, 
 0x10,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x09, 
 0xc3,  0xea,  0x63,  0x3f,  0x10,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x09,  0xf3,  0x69,  0xa4,  0xde,  0x0b,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0xe1,  0x43,  0xce,  0x6d,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x02,  0x06,  0xda,  0x39,  0xee,  0xf1,  0xc6,  0xa1,  0x08,  0xd2,  0xb6,  0x72,  0x73,  0x7b, 
 0xf5,  0x94,  0xd8,  0x5d,  0x84,  0xbf,  0x00,  0x00,  0x54,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x44,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0xf1,  0x61,  0x1f,  0xf5,  0xdb,  0x0b, 
 0xf3,  0x3d,  0xd9,  0x7c,  0x4e,  0xfe,  0x81,  0x0a,  0x45,  0xe6,  0x7e,  0x16,  0x70,  0x00,  0x00,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0xbf,  0x88,  0xce,  0x87, 
 0x0c,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0xc3,  0x43,  0x81,  0x66, 
 0xf1,  0x61,  0x1f,  0xf5,  0xdb,  0x0b,  0xf3,  0x3d,  0xd9,  0x7c,  0x4e,  0xfe,  0x81,  0x0a,  0x45,  0x00, 
 0x33,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00,  0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x23,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x04,  0x0b,  0x39,  0x9b,  0x59,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x07,  0xce,  0x1c,  0x29,  0x9a,  0x00,  0x77,  0x02,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0xf2,  0xcd,  0xb1,  0x1c,  0x6a,  0xff,  0xa6,  0x21,  0x13,  0x56,  0x56,  0xa6,  0xba,  0x34,  0x0a,  0x00, 
 0x2b,  0x01,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x2b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x23,  0x00,  0x00,  0x00,  0x72,  0x6f,  0x62,  0x6f,  0x74,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a, 
 0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x41,  0x72,  0x6d,  0x43,  0x6f, 
 0x6e,  0x74,  0x72,  0x6f,  0x6c,  0x5f,  0x00,  0x00,  0xf3,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00, 
 0x26,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0xf2,  0x07,  0xb1,  0x13,  0x02,  0x50, 
 0x4f,  0xea,  0x69,  0xec,  0xda,  0xe3,  0x35,  0xa6,  0xa4,  0x00,  0x00,  0x00,  0x08,  0x00,  0x00,  0x00, 
 0x68,  0x65,  0x61,  0x64,  0x65,  0x72,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00,  0x05,  0x00,  0x00,  0x00,  0x61,  0x72,  0x6d,  0x5f, 
 0x00,  0x00,  0x00,  0x00,  0x1b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00, 
 0x0d,  0x00,  0x00,  0x00,  0x6d,  0x6f,  0x74,  0x69,  0x6f,  0x6e,  0x5f,  0x74,  0x79,  0x70,  0x65,  0x5f, 
 0x00,  0x00,  0x00,  0x00,  0x1f,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x09,  0x0d,  0x00,  0x00,  0x00,  0x68,  0x61,  0x6e,  0x64,  0x5f,  0x74,  0x61,  0x72, 
 0x67,  0x65,  0x74,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x1e,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x09,  0x0c,  0x00,  0x00,  0x00,  0x61,  0x72,  0x6d,  0x5f, 
 0x74,  0x61,  0x72,  0x67,  0x65,  0x74,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x76,  0x65,  0x6c,  0x6f, 
 0x63,  0x69,  0x74,  0x79,  0x5f,  0x00,  0x00,  0x00,  0x23,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x02,  0x00,  0x15,  0x00,  0x00,  0x00,  0x63,  0x68,  0x61,  0x6e,  0x67,  0x65,  0x5f,  0x6d, 
 0x6f,  0x74,  0x69,  0x6f,  0x6e,  0x5f,  0x73,  0x74,  0x61,  0x74,  0x65,  0x5f,  0x00,  0x00,  0x00,  0xf2, 
 0x07,  0xb1,  0x13,  0x02,  0x50,  0x4f,  0xea,  0x69,  0xec,  0xda,  0xe3,  0x35,  0xa6,  0xa4,  0x00,  0x00, 
 0x97,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x28,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x20,  0x00,  0x00,  0x00,  0x63,  0x6f,  0x6d,  0x6d,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x5a,  0x56,  0x48,  0x65,  0x61,  0x64, 
 0x65,  0x72,  0x5f,  0x00,  0x63,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0xf2,  0x3a,  0x59,  0xec,  0xdf,  0x8b,  0x02,  0x2e,  0x2f,  0x1c, 
 0xf7,  0xec,  0x59,  0x8a,  0xd1,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x74,  0x69,  0x6d,  0x65, 
 0x5f,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00, 
 0x0a,  0x00,  0x00,  0x00,  0x74,  0x72,  0x61,  0x63,  0x65,  0x5f,  0x69,  0x64,  0x5f,  0x00,  0x00,  0x00, 
 0x17,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x09,  0x00,  0x00,  0x00, 
 0x72,  0x65,  0x73,  0x65,  0x72,  0x76,  0x65,  0x5f,  0x00,  0x00,  0x00,  0xf2,  0x3a,  0x59,  0xec,  0xdf, 
 0x8b,  0x02,  0x2e,  0x2f,  0x1c,  0xf7,  0xec,  0x59,  0x8a,  0xd1,  0x00,  0x00,  0x73,  0x00,  0x00,  0x00, 
 0xf2,  0x51,  0x01,  0x00,  0x2d,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x25,  0x00,  0x00,  0x00, 
 0x62,  0x75,  0x69,  0x6c,  0x74,  0x69,  0x6e,  0x5f,  0x69,  0x6e,  0x74,  0x65,  0x72,  0x66,  0x61,  0x63, 
 0x65,  0x73,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x54, 
 0x69,  0x6d,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x37,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x13,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x73,  0x65,  0x63,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x07,  0x00,  0x09,  0x00,  0x00,  0x00,  0x6e,  0x61,  0x6e,  0x6f,  0x73,  0x65,  0x63,  0x5f, 
 0x00,  0x00,  0x00,  0x00,  0x5e,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0xf2,  0xcd,  0xb1,  0x1c, 
 0x6a,  0xff,  0xa6,  0x21,  0x13,  0x56,  0x56,  0xa6,  0xba,  0x34,  0x0a,  0xf1,  0x27,  0x8b,  0xfa,  0x05, 
 0x95,  0x59,  0x28,  0x93,  0x69,  0x93,  0xae,  0x4e,  0x52,  0x9f,  0xf2,  0x07,  0xb1,  0x13,  0x02,  0x50, 
 0x4f,  0xea,  0x69,  0xec,  0xda,  0xe3,  0x35,  0xa6,  0xa4,  0xf1,  0xc6,  0xa1,  0x08,  0xd2,  0xb6,  0x72, 
 0x73,  0x7b,  0xf5,  0x94,  0xd8,  0x5d,  0x84,  0xbf,  0xf2,  0x3a,  0x59,  0xec,  0xdf,  0x8b,  0x02,  0x2e, 
 0x2f,  0x1c,  0xf7,  0xec,  0x59,  0x8a,  0xd1,  0xf1,  0x61,  0x1f,  0xf5,  0xdb,  0x0b,  0xf3,  0x3d,  0xd9, 
 0x7c,  0x4e,  0xfe,  0x81,  0x0a,  0x45, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::ArmControl_>::type_info_blob() {
  static const uint8_t blob[] = {
 0xc0,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x58,  0x00,  0x00,  0x00,  0x54,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x27,  0x8b,  0xfa,  0x05,  0x95,  0x59,  0x28,  0x93,  0x69,  0x93,  0xae, 
 0x4e,  0x52,  0x9f,  0x00,  0x9f,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x34,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf1,  0xc6,  0xa1,  0x08,  0xd2,  0xb6,  0x72,  0x73, 
 0x7b,  0xf5,  0x94,  0xd8,  0x5d,  0x84,  0xbf,  0x00,  0x58,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00, 
 0xf1,  0x61,  0x1f,  0xf5,  0xdb,  0x0b,  0xf3,  0x3d,  0xd9,  0x7c,  0x4e,  0xfe,  0x81,  0x0a,  0x45,  0x00, 
 0x37,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x58,  0x00,  0x00,  0x00,  0x54,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xcd,  0xb1,  0x1c,  0x6a,  0xff,  0xa6,  0x21,  0x13,  0x56,  0x56,  0xa6, 
 0xba,  0x34,  0x0a,  0x00,  0x2f,  0x01,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x34,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf2,  0x07,  0xb1,  0x13,  0x02,  0x50,  0x4f,  0xea, 
 0x69,  0xec,  0xda,  0xe3,  0x35,  0xa6,  0xa4,  0x00,  0x9b,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00, 
 0xf2,  0x3a,  0x59,  0xec,  0xdf,  0x8b,  0x02,  0x2e,  0x2f,  0x1c,  0xf7,  0xec,  0x59,  0x8a,  0xd1,  0x00, 
 0x77,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::robot_msgs::msg::dds_::ArmControl_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::robot_msgs::msg::dds_::ArmControl_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::robot_msgs::msg::dds_::ArmControl_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::robot_msgs::msg::dds_::ArmControl_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::robot_msgs::msg::dds_::ArmControl_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.header_(), prop))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.arm_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.motion_type_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.hand_target_().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.hand_target_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.arm_target_().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.arm_target_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.velocity_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.change_motion_state_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::robot_msgs::msg::dds_::ArmControl_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::ArmControl_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::robot_msgs::msg::dds_::ArmControl_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.header_(), prop))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.arm_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.motion_type_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.hand_target_().size());
      if (!read(streamer, se_1))
        return false;
      instance.hand_target_().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.hand_target_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.arm_target_().size());
      if (!read(streamer, se_1))
        return false;
      instance.arm_target_().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.arm_target_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.velocity_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.change_motion_state_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::robot_msgs::msg::dds_::ArmControl_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::ArmControl_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::robot_msgs::msg::dds_::ArmControl_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.header_(), prop))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.arm_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.motion_type_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.hand_target_().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.arm_target_().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.velocity_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.change_motion_state_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::robot_msgs::msg::dds_::ArmControl_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::ArmControl_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::robot_msgs::msg::dds_::ArmControl_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.header_(), prop))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.arm_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.motion_type_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.velocity_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.change_motion_state_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::robot_msgs::msg::dds_::ArmControl_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::ArmControl_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_ARMCONTROL__HPP
