/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: ErrorReport_.idl
  Source: ErrorReport_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_ERRORREPORT__HPP
#define DDSCXX_ERRORREPORT__HPP

#include <cstdint>
#include <string>

namespace robot_msgs
{
namespace msg
{
namespace dds_
{
class ErrorReport_
{
private:
 uint8_t part__ = 0;
 uint8_t subpart__ = 0;
 uint8_t err__ = 0;
 std::string level__;
 std::string description__;
 std::string code__;

public:
  ErrorReport_() = default;

  explicit ErrorReport_(
    uint8_t part_,
    uint8_t subpart_,
    uint8_t err_,
    const std::string& level_,
    const std::string& description_,
    const std::string& code_) :
    part__(part_),
    subpart__(subpart_),
    err__(err_),
    level__(level_),
    description__(description_),
    code__(code_) { }

  uint8_t part_() const { return this->part__; }
  uint8_t& part_() { return this->part__; }
  void part_(uint8_t _val_) { this->part__ = _val_; }
  uint8_t subpart_() const { return this->subpart__; }
  uint8_t& subpart_() { return this->subpart__; }
  void subpart_(uint8_t _val_) { this->subpart__ = _val_; }
  uint8_t err_() const { return this->err__; }
  uint8_t& err_() { return this->err__; }
  void err_(uint8_t _val_) { this->err__ = _val_; }
  const std::string& level_() const { return this->level__; }
  std::string& level_() { return this->level__; }
  void level_(const std::string& _val_) { this->level__ = _val_; }
  void level_(std::string&& _val_) { this->level__ = _val_; }
  const std::string& description_() const { return this->description__; }
  std::string& description_() { return this->description__; }
  void description_(const std::string& _val_) { this->description__ = _val_; }
  void description_(std::string&& _val_) { this->description__ = _val_; }
  const std::string& code_() const { return this->code__; }
  std::string& code_() { return this->code__; }
  void code_(const std::string& _val_) { this->code__ = _val_; }
  void code_(std::string&& _val_) { this->code__ = _val_; }

  bool operator==(const ErrorReport_& _other) const
  {
    (void) _other;
    return part__ == _other.part__ &&
      subpart__ == _other.subpart__ &&
      err__ == _other.err__ &&
      level__ == _other.level__ &&
      description__ == _other.description__ &&
      code__ == _other.code__;
  }

  bool operator!=(const ErrorReport_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::robot_msgs::msg::dds_::ErrorReport_>::getTypeName()
{
  return "robot_msgs::msg::dds_::ErrorReport_";
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::ErrorReport_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::ErrorReport_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::ErrorReport_>::type_map_blob_sz() { return 430; }
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::ErrorReport_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::ErrorReport_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x8c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x30,  0x54,  0xa4,  0xc0,  0xac,  0xd5,  0x5c, 
 0x4d,  0x05,  0xbc,  0x2d,  0xdd,  0x53,  0x3f,  0x00,  0x74,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x64,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0xe9,  0xc2,  0x46,  0x43,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x1f,  0x51,  0xee,  0x19,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x6b,  0xe9,  0x7f,  0x3e,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x54,  0x2d,  0xfb,  0x3f, 
 0x0c,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x1e,  0xff,  0xf2,  0x53, 
 0x0c,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x0c,  0xc6,  0x89,  0x31, 
 0xf4,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x01,  0xb6,  0xa9,  0xc7,  0xef,  0x8b,  0x32, 
 0xa0,  0xc8,  0x90,  0x9f,  0x06,  0x8a,  0x5d,  0x00,  0xdc,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x2c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00,  0x72,  0x6f,  0x62,  0x6f, 
 0x74,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73, 
 0x5f,  0x3a,  0x3a,  0x45,  0x72,  0x72,  0x6f,  0x72,  0x52,  0x65,  0x70,  0x6f,  0x72,  0x74,  0x5f,  0x00, 
 0xa4,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x02,  0x00,  0x06,  0x00,  0x00,  0x00,  0x70,  0x61,  0x72,  0x74,  0x5f,  0x00,  0x00,  0x00, 
 0x17,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00,  0x09,  0x00,  0x00,  0x00, 
 0x73,  0x75,  0x62,  0x70,  0x61,  0x72,  0x74,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00,  0x05,  0x00,  0x00,  0x00,  0x65,  0x72,  0x72,  0x5f, 
 0x00,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00, 
 0x07,  0x00,  0x00,  0x00,  0x6c,  0x65,  0x76,  0x65,  0x6c,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x1b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x0d,  0x00,  0x00,  0x00, 
 0x64,  0x65,  0x73,  0x63,  0x72,  0x69,  0x70,  0x74,  0x69,  0x6f,  0x6e,  0x5f,  0x00,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x63,  0x6f,  0x64,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0xf2,  0x01,  0xb6,  0xa9,  0xc7,  0xef,  0x8b,  0x32,  0xa0,  0xc8,  0x90,  0x9f,  0x06,  0x8a,  0x5d,  0xf1, 
 0x30,  0x54,  0xa4,  0xc0,  0xac,  0xd5,  0x5c,  0x4d,  0x05,  0xbc,  0x2d,  0xdd,  0x53,  0x3f, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::ErrorReport_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x30,  0x54,  0xa4,  0xc0,  0xac,  0xd5,  0x5c,  0x4d,  0x05,  0xbc,  0x2d, 
 0xdd,  0x53,  0x3f,  0x00,  0x78,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x01,  0xb6,  0xa9,  0xc7,  0xef,  0x8b,  0x32,  0xa0,  0xc8,  0x90,  0x9f, 
 0x06,  0x8a,  0x5d,  0x00,  0xe0,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::robot_msgs::msg::dds_::ErrorReport_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::robot_msgs::msg::dds_::ErrorReport_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::robot_msgs::msg::dds_::ErrorReport_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::robot_msgs::msg::dds_::ErrorReport_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::robot_msgs::msg::dds_::ErrorReport_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.part_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.subpart_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.err_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.level_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.description_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.code_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::robot_msgs::msg::dds_::ErrorReport_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::ErrorReport_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::robot_msgs::msg::dds_::ErrorReport_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.part_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.subpart_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.err_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.level_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.description_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.code_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::robot_msgs::msg::dds_::ErrorReport_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::ErrorReport_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::robot_msgs::msg::dds_::ErrorReport_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.part_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.subpart_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.err_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.level_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.description_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.code_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::robot_msgs::msg::dds_::ErrorReport_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::ErrorReport_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::robot_msgs::msg::dds_::ErrorReport_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.part_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.subpart_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.err_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.level_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.description_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.code_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::robot_msgs::msg::dds_::ErrorReport_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::ErrorReport_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_ERRORREPORT__HPP
