/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: EulerAngle_.idl
  Source: EulerAngle_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_EULERANGLE__HPP
#define DDSCXX_EULERANGLE__HPP


namespace yesense_interface
{
namespace msg
{
namespace dds_
{
class EulerAngle_
{
private:
 float pitch__ = 0.0f;
 float roll__ = 0.0f;
 float yaw__ = 0.0f;

public:
  EulerAngle_() = default;

  explicit EulerAngle_(
    float pitch_,
    float roll_,
    float yaw_) :
    pitch__(pitch_),
    roll__(roll_),
    yaw__(yaw_) { }

  float pitch_() const { return this->pitch__; }
  float& pitch_() { return this->pitch__; }
  void pitch_(float _val_) { this->pitch__ = _val_; }
  float roll_() const { return this->roll__; }
  float& roll_() { return this->roll__; }
  void roll_(float _val_) { this->roll__ = _val_; }
  float yaw_() const { return this->yaw__; }
  float& yaw_() { return this->yaw__; }
  void yaw_(float _val_) { this->yaw__ = _val_; }

  bool operator==(const EulerAngle_& _other) const
  {
    (void) _other;
    return pitch__ == _other.pitch__ &&
      roll__ == _other.roll__ &&
      yaw__ == _other.yaw__;
  }

  bool operator!=(const EulerAngle_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::yesense_interface::msg::dds_::EulerAngle_>::getTypeName()
{
  return "yesense_interface::msg::dds_::EulerAngle_";
}

template <> constexpr bool TopicTraits<::yesense_interface::msg::dds_::EulerAngle_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::EulerAngle_>::type_map_blob_sz() { return 306; }
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::EulerAngle_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::EulerAngle_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x5b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x4e,  0x04,  0x7d,  0x85,  0xac,  0xbe,  0x10, 
 0xe8,  0xd4,  0x11,  0x83,  0x3c,  0xe1,  0x41,  0x00,  0x43,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x33,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xfc,  0x9b,  0xdd,  0x2d,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x63,  0xad,  0xa9,  0x80,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xd9,  0xca,  0xc6,  0xc5,  0x00, 
 0xa7,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x3d,  0x9f,  0xa1,  0xa1,  0xed,  0x6d,  0x0b, 
 0x85,  0x00,  0xa5,  0x66,  0xda,  0xc7,  0x90,  0x00,  0x8f,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x32,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x2a,  0x00,  0x00,  0x00,  0x79,  0x65,  0x73,  0x65, 
 0x6e,  0x73,  0x65,  0x5f,  0x69,  0x6e,  0x74,  0x65,  0x72,  0x66,  0x61,  0x63,  0x65,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x45,  0x75,  0x6c,  0x65,  0x72,  0x41, 
 0x6e,  0x67,  0x6c,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x4f,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x15,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x07,  0x00,  0x00,  0x00, 
 0x70,  0x69,  0x74,  0x63,  0x68,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x06,  0x00,  0x00,  0x00,  0x72,  0x6f,  0x6c,  0x6c, 
 0x5f,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x79,  0x61,  0x77,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0xf2,  0x3d,  0x9f,  0xa1,  0xa1,  0xed,  0x6d,  0x0b,  0x85,  0x00,  0xa5,  0x66, 
 0xda,  0xc7,  0x90,  0xf1,  0x4e,  0x04,  0x7d,  0x85,  0xac,  0xbe,  0x10,  0xe8,  0xd4,  0x11,  0x83,  0x3c, 
 0xe1,  0x41, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::EulerAngle_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x4e,  0x04,  0x7d,  0x85,  0xac,  0xbe,  0x10,  0xe8,  0xd4,  0x11,  0x83, 
 0x3c,  0xe1,  0x41,  0x00,  0x47,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x3d,  0x9f,  0xa1,  0xa1,  0xed,  0x6d,  0x0b,  0x85,  0x00,  0xa5,  0x66, 
 0xda,  0xc7,  0x90,  0x00,  0x93,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::yesense_interface::msg::dds_::EulerAngle_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::yesense_interface::msg::dds_::EulerAngle_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::yesense_interface::msg::dds_::EulerAngle_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::yesense_interface::msg::dds_::EulerAngle_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::yesense_interface::msg::dds_::EulerAngle_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.pitch_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.roll_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.yaw_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::yesense_interface::msg::dds_::EulerAngle_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::EulerAngle_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::yesense_interface::msg::dds_::EulerAngle_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.pitch_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.roll_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.yaw_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::yesense_interface::msg::dds_::EulerAngle_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::EulerAngle_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::yesense_interface::msg::dds_::EulerAngle_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.pitch_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.roll_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.yaw_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::yesense_interface::msg::dds_::EulerAngle_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::EulerAngle_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::yesense_interface::msg::dds_::EulerAngle_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.pitch_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.roll_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.yaw_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::yesense_interface::msg::dds_::EulerAngle_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::EulerAngle_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_EULERANGLE__HPP
