/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: GnssPos_.idl
  Source: GnssPos_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_GNSSPOS__HPP
#define DDSCXX_GNSSPOS__HPP


namespace yesense_interface
{
namespace msg
{
namespace dds_
{
class GnssPos_
{
private:
 double longitude__ = 0.0;
 double latitude__ = 0.0;
 float altitude__ = 0.0f;

public:
  GnssPos_() = default;

  explicit GnssPos_(
    double longitude_,
    double latitude_,
    float altitude_) :
    longitude__(longitude_),
    latitude__(latitude_),
    altitude__(altitude_) { }

  double longitude_() const { return this->longitude__; }
  double& longitude_() { return this->longitude__; }
  void longitude_(double _val_) { this->longitude__ = _val_; }
  double latitude_() const { return this->latitude__; }
  double& latitude_() { return this->latitude__; }
  void latitude_(double _val_) { this->latitude__ = _val_; }
  float altitude_() const { return this->altitude__; }
  float& altitude_() { return this->altitude__; }
  void altitude_(float _val_) { this->altitude__ = _val_; }

  bool operator==(const GnssPos_& _other) const
  {
    (void) _other;
    return longitude__ == _other.longitude__ &&
      latitude__ == _other.latitude__ &&
      altitude__ == _other.altitude__;
  }

  bool operator!=(const GnssPos_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::yesense_interface::msg::dds_::GnssPos_>::getTypeName()
{
  return "yesense_interface::msg::dds_::GnssPos_";
}

template <> constexpr bool TopicTraits<::yesense_interface::msg::dds_::GnssPos_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::GnssPos_>::type_map_blob_sz() { return 314; }
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::GnssPos_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::GnssPos_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x5b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x9b,  0x9d,  0x77,  0x27,  0x75,  0x24,  0xa9, 
 0xc7,  0x5c,  0x7c,  0xc3,  0xb9,  0xa1,  0x5f,  0x00,  0x43,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x33,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0xc5,  0x11,  0xd4,  0x78,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0xb1,  0xf7,  0x49,  0x96,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x8e,  0xf8,  0x77,  0x58,  0x00, 
 0xb0,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x5a,  0x5c,  0xc7,  0xd6,  0x9d,  0x3a,  0xfe, 
 0x9f,  0x10,  0x07,  0xca,  0xa3,  0xc0,  0x47,  0x00,  0x98,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x2f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x27,  0x00,  0x00,  0x00,  0x79,  0x65,  0x73,  0x65, 
 0x6e,  0x73,  0x65,  0x5f,  0x69,  0x6e,  0x74,  0x65,  0x72,  0x66,  0x61,  0x63,  0x65,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x47,  0x6e,  0x73,  0x73,  0x50,  0x6f, 
 0x73,  0x5f,  0x00,  0x00,  0x5c,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x6c,  0x6f,  0x6e,  0x67, 
 0x69,  0x74,  0x75,  0x64,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x6c,  0x61,  0x74,  0x69, 
 0x74,  0x75,  0x64,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x61,  0x6c,  0x74,  0x69,  0x74,  0x75,  0x64,  0x65, 
 0x5f,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x5a,  0x5c,  0xc7, 
 0xd6,  0x9d,  0x3a,  0xfe,  0x9f,  0x10,  0x07,  0xca,  0xa3,  0xc0,  0x47,  0xf1,  0x9b,  0x9d,  0x77,  0x27, 
 0x75,  0x24,  0xa9,  0xc7,  0x5c,  0x7c,  0xc3,  0xb9,  0xa1,  0x5f, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::GnssPos_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x9b,  0x9d,  0x77,  0x27,  0x75,  0x24,  0xa9,  0xc7,  0x5c,  0x7c,  0xc3, 
 0xb9,  0xa1,  0x5f,  0x00,  0x47,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x5a,  0x5c,  0xc7,  0xd6,  0x9d,  0x3a,  0xfe,  0x9f,  0x10,  0x07,  0xca, 
 0xa3,  0xc0,  0x47,  0x00,  0x9c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::yesense_interface::msg::dds_::GnssPos_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::yesense_interface::msg::dds_::GnssPos_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::yesense_interface::msg::dds_::GnssPos_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::yesense_interface::msg::dds_::GnssPos_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::yesense_interface::msg::dds_::GnssPos_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.longitude_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.latitude_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.altitude_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::yesense_interface::msg::dds_::GnssPos_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::GnssPos_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::yesense_interface::msg::dds_::GnssPos_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.longitude_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.latitude_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.altitude_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::yesense_interface::msg::dds_::GnssPos_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::GnssPos_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::yesense_interface::msg::dds_::GnssPos_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.longitude_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.latitude_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.altitude_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::yesense_interface::msg::dds_::GnssPos_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::GnssPos_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::yesense_interface::msg::dds_::GnssPos_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.longitude_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.latitude_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.altitude_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::yesense_interface::msg::dds_::GnssPos_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::GnssPos_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_GNSSPOS__HPP
