/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: JointCmd_.idl
  Source: JointCmd_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_JOINTCMD__HPP
#define DDSCXX_JOINTCMD__HPP


namespace robot_msgs
{
namespace msg
{
namespace dds_
{
class JointCmd_
{
private:
 double joint_pos__ = 0.0;
 double joint_vel__ = 0.0;
 double joint_torque__ = 0.0;
 double kp__ = 0.0;
 double kd__ = 0.0;

public:
  JointCmd_() = default;

  explicit JointCmd_(
    double joint_pos_,
    double joint_vel_,
    double joint_torque_,
    double kp_,
    double kd_) :
    joint_pos__(joint_pos_),
    joint_vel__(joint_vel_),
    joint_torque__(joint_torque_),
    kp__(kp_),
    kd__(kd_) { }

  double joint_pos_() const { return this->joint_pos__; }
  double& joint_pos_() { return this->joint_pos__; }
  void joint_pos_(double _val_) { this->joint_pos__ = _val_; }
  double joint_vel_() const { return this->joint_vel__; }
  double& joint_vel_() { return this->joint_vel__; }
  void joint_vel_(double _val_) { this->joint_vel__ = _val_; }
  double joint_torque_() const { return this->joint_torque__; }
  double& joint_torque_() { return this->joint_torque__; }
  void joint_torque_(double _val_) { this->joint_torque__ = _val_; }
  double kp_() const { return this->kp__; }
  double& kp_() { return this->kp__; }
  void kp_(double _val_) { this->kp__ = _val_; }
  double kd_() const { return this->kd__; }
  double& kd_() { return this->kd__; }
  void kd_(double _val_) { this->kd__ = _val_; }

  bool operator==(const JointCmd_& _other) const
  {
    (void) _other;
    return joint_pos__ == _other.joint_pos__ &&
      joint_vel__ == _other.joint_vel__ &&
      joint_torque__ == _other.joint_torque__ &&
      kp__ == _other.kp__ &&
      kd__ == _other.kd__;
  }

  bool operator!=(const JointCmd_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::robot_msgs::msg::dds_::JointCmd_>::getTypeName()
{
  return "robot_msgs::msg::dds_::JointCmd_";
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::JointCmd_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::JointCmd_>::type_map_blob_sz() { return 398; }
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::JointCmd_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::JointCmd_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x7b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xb6,  0x58,  0x09,  0x48,  0xf4,  0x55,  0xd9, 
 0x72,  0xbf,  0x77,  0x5f,  0xda,  0x0e,  0x2c,  0x00,  0x63,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x53,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x06,  0x1b,  0x26,  0xf8,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0xfd,  0xf3,  0x1d,  0x75,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x65,  0x3f,  0x72,  0x49,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x27,  0x26,  0x80,  0x3f,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x79,  0xe6,  0xc0,  0x52,  0x00, 
 0xe2,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x65,  0xfd,  0xed,  0x99,  0x34,  0x9d,  0x62, 
 0x0e,  0x42,  0xe9,  0xbc,  0x06,  0x37,  0x6b,  0x00,  0xca,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x29,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x21,  0x00,  0x00,  0x00,  0x72,  0x6f,  0x62,  0x6f, 
 0x74,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73, 
 0x5f,  0x3a,  0x3a,  0x4a,  0x6f,  0x69,  0x6e,  0x74,  0x43,  0x6d,  0x64,  0x5f,  0x00,  0x00,  0x00,  0x00, 
 0x92,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x0a,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x70,  0x6f, 
 0x73,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x0a,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x76,  0x65, 
 0x6c,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x0a,  0x00,  0x0e,  0x00,  0x00,  0x00,  0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x74,  0x6f, 
 0x72,  0x71,  0x75,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x12,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x0a,  0x00,  0x04,  0x00,  0x00,  0x00,  0x6b,  0x70,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x12,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x6b,  0x64,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0xf2,  0x65,  0xfd,  0xed,  0x99,  0x34,  0x9d,  0x62,  0x0e,  0x42,  0xe9,  0xbc,  0x06,  0x37,  0x6b,  0xf1, 
 0xb6,  0x58,  0x09,  0x48,  0xf4,  0x55,  0xd9,  0x72,  0xbf,  0x77,  0x5f,  0xda,  0x0e,  0x2c, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::JointCmd_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xb6,  0x58,  0x09,  0x48,  0xf4,  0x55,  0xd9,  0x72,  0xbf,  0x77,  0x5f, 
 0xda,  0x0e,  0x2c,  0x00,  0x67,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x65,  0xfd,  0xed,  0x99,  0x34,  0x9d,  0x62,  0x0e,  0x42,  0xe9,  0xbc, 
 0x06,  0x37,  0x6b,  0x00,  0xce,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::robot_msgs::msg::dds_::JointCmd_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::robot_msgs::msg::dds_::JointCmd_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::robot_msgs::msg::dds_::JointCmd_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::robot_msgs::msg::dds_::JointCmd_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::robot_msgs::msg::dds_::JointCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.joint_pos_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.joint_vel_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.joint_torque_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.kp_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.kd_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::robot_msgs::msg::dds_::JointCmd_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::JointCmd_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::robot_msgs::msg::dds_::JointCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.joint_pos_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.joint_vel_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.joint_torque_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.kp_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.kd_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::robot_msgs::msg::dds_::JointCmd_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::JointCmd_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::robot_msgs::msg::dds_::JointCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.joint_pos_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.joint_vel_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.joint_torque_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.kp_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.kd_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::robot_msgs::msg::dds_::JointCmd_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::JointCmd_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::robot_msgs::msg::dds_::JointCmd_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.joint_pos_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.joint_vel_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.joint_torque_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.kp_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.kd_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::robot_msgs::msg::dds_::JointCmd_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::JointCmd_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_JOINTCMD__HPP
