/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: NavStatus_.idl
  Source: NavStatus_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_NAVSTATUS__HPP
#define DDSCXX_NAVSTATUS__HPP

#include <cstdint>

namespace yesense_interface
{
namespace msg
{
namespace dds_
{
class NavStatus_
{
private:
 uint8_t fusion_status__ = 0;
 uint8_t gnss_status__ = 0;

public:
  NavStatus_() = default;

  explicit NavStatus_(
    uint8_t fusion_status_,
    uint8_t gnss_status_) :
    fusion_status__(fusion_status_),
    gnss_status__(gnss_status_) { }

  uint8_t fusion_status_() const { return this->fusion_status__; }
  uint8_t& fusion_status_() { return this->fusion_status__; }
  void fusion_status_(uint8_t _val_) { this->fusion_status__ = _val_; }
  uint8_t gnss_status_() const { return this->gnss_status__; }
  uint8_t& gnss_status_() { return this->gnss_status__; }
  void gnss_status_(uint8_t _val_) { this->gnss_status__ = _val_; }

  bool operator==(const NavStatus_& _other) const
  {
    (void) _other;
    return fusion_status__ == _other.fusion_status__ &&
      gnss_status__ == _other.gnss_status__;
  }

  bool operator!=(const NavStatus_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::yesense_interface::msg::dds_::NavStatus_>::getTypeName()
{
  return "yesense_interface::msg::dds_::NavStatus_";
}

template <> constexpr bool TopicTraits<::yesense_interface::msg::dds_::NavStatus_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::NavStatus_>::type_map_blob_sz() { return 282; }
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::NavStatus_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::NavStatus_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x4b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xd7,  0x0e,  0x2d,  0x5b,  0x93,  0xa6,  0x89, 
 0xdc,  0xf9,  0x7b,  0x3e,  0xdd,  0x9d,  0x7c,  0x00,  0x33,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x23,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x10,  0x01,  0x47,  0x1a,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0xdd,  0x42,  0x7d,  0xfa,  0x00, 
 0x9f,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x82,  0x7a,  0xe9,  0xed,  0xbe,  0x0e,  0x90, 
 0xfc,  0x70,  0x51,  0x2b,  0x65,  0x3c,  0x3e,  0x00,  0x87,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x31,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x29,  0x00,  0x00,  0x00,  0x79,  0x65,  0x73,  0x65, 
 0x6e,  0x73,  0x65,  0x5f,  0x69,  0x6e,  0x74,  0x65,  0x72,  0x66,  0x61,  0x63,  0x65,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x4e,  0x61,  0x76,  0x53,  0x74,  0x61, 
 0x74,  0x75,  0x73,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x47,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x1d,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00,  0x0f,  0x00,  0x00,  0x00, 
 0x66,  0x75,  0x73,  0x69,  0x6f,  0x6e,  0x5f,  0x73,  0x74,  0x61,  0x74,  0x75,  0x73,  0x5f,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x1b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00, 
 0x0d,  0x00,  0x00,  0x00,  0x67,  0x6e,  0x73,  0x73,  0x5f,  0x73,  0x74,  0x61,  0x74,  0x75,  0x73,  0x5f, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x82,  0x7a,  0xe9, 
 0xed,  0xbe,  0x0e,  0x90,  0xfc,  0x70,  0x51,  0x2b,  0x65,  0x3c,  0x3e,  0xf1,  0xd7,  0x0e,  0x2d,  0x5b, 
 0x93,  0xa6,  0x89,  0xdc,  0xf9,  0x7b,  0x3e,  0xdd,  0x9d,  0x7c, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::NavStatus_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xd7,  0x0e,  0x2d,  0x5b,  0x93,  0xa6,  0x89,  0xdc,  0xf9,  0x7b,  0x3e, 
 0xdd,  0x9d,  0x7c,  0x00,  0x37,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x82,  0x7a,  0xe9,  0xed,  0xbe,  0x0e,  0x90,  0xfc,  0x70,  0x51,  0x2b, 
 0x65,  0x3c,  0x3e,  0x00,  0x8b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::yesense_interface::msg::dds_::NavStatus_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::yesense_interface::msg::dds_::NavStatus_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::yesense_interface::msg::dds_::NavStatus_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::yesense_interface::msg::dds_::NavStatus_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::yesense_interface::msg::dds_::NavStatus_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.fusion_status_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.gnss_status_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::yesense_interface::msg::dds_::NavStatus_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::NavStatus_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::yesense_interface::msg::dds_::NavStatus_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.fusion_status_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.gnss_status_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::yesense_interface::msg::dds_::NavStatus_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::NavStatus_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::yesense_interface::msg::dds_::NavStatus_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.fusion_status_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.gnss_status_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::yesense_interface::msg::dds_::NavStatus_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::NavStatus_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::yesense_interface::msg::dds_::NavStatus_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.fusion_status_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.gnss_status_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::yesense_interface::msg::dds_::NavStatus_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::NavStatus_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_NAVSTATUS__HPP
