/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: Pressure_.idl
  Source: Pressure_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_PRESSURE__HPP
#define DDSCXX_PRESSURE__HPP


namespace yesense_interface
{
namespace msg
{
namespace dds_
{
class Pressure_
{
private:
 float val__ = 0.0f;

public:
  Pressure_() = default;

  explicit Pressure_(
    float val_) :
    val__(val_) { }

  float val_() const { return this->val__; }
  float& val_() { return this->val__; }
  void val_(float _val_) { this->val__ = _val_; }

  bool operator==(const Pressure_& _other) const
  {
    (void) _other;
    return val__ == _other.val__;
  }

  bool operator!=(const Pressure_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::yesense_interface::msg::dds_::Pressure_>::getTypeName()
{
  return "yesense_interface::msg::dds_::Pressure_";
}

template <> constexpr bool TopicTraits<::yesense_interface::msg::dds_::Pressure_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::Pressure_>::type_map_blob_sz() { return 218; }
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::Pressure_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::Pressure_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x3b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xc5,  0x4e,  0x1f,  0x07,  0x57,  0xd8,  0xc7, 
 0xca,  0xae,  0x14,  0xa2,  0x32,  0x8a,  0xa0,  0x00,  0x23,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xd7,  0x1f,  0xe6,  0x5d,  0x00, 
 0x6f,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xfc,  0x8f,  0x15,  0xd2,  0x14,  0xaf,  0x4e, 
 0x1b,  0x36,  0x62,  0x35,  0x98,  0x68,  0xe6,  0x00,  0x57,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x30,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x28,  0x00,  0x00,  0x00,  0x79,  0x65,  0x73,  0x65, 
 0x6e,  0x73,  0x65,  0x5f,  0x69,  0x6e,  0x74,  0x65,  0x72,  0x66,  0x61,  0x63,  0x65,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x50,  0x72,  0x65,  0x73,  0x73,  0x75, 
 0x72,  0x65,  0x5f,  0x00,  0x1b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x05,  0x00,  0x00,  0x00,  0x76,  0x61,  0x6c,  0x5f, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xfc,  0x8f,  0x15, 
 0xd2,  0x14,  0xaf,  0x4e,  0x1b,  0x36,  0x62,  0x35,  0x98,  0x68,  0xe6,  0xf1,  0xc5,  0x4e,  0x1f,  0x07, 
 0x57,  0xd8,  0xc7,  0xca,  0xae,  0x14,  0xa2,  0x32,  0x8a,  0xa0, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::Pressure_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xc5,  0x4e,  0x1f,  0x07,  0x57,  0xd8,  0xc7,  0xca,  0xae,  0x14,  0xa2, 
 0x32,  0x8a,  0xa0,  0x00,  0x27,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xfc,  0x8f,  0x15,  0xd2,  0x14,  0xaf,  0x4e,  0x1b,  0x36,  0x62,  0x35, 
 0x98,  0x68,  0xe6,  0x00,  0x5b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::yesense_interface::msg::dds_::Pressure_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::yesense_interface::msg::dds_::Pressure_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::yesense_interface::msg::dds_::Pressure_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::yesense_interface::msg::dds_::Pressure_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::yesense_interface::msg::dds_::Pressure_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.val_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::yesense_interface::msg::dds_::Pressure_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::Pressure_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::yesense_interface::msg::dds_::Pressure_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.val_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::yesense_interface::msg::dds_::Pressure_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::Pressure_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::yesense_interface::msg::dds_::Pressure_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.val_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::yesense_interface::msg::dds_::Pressure_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::Pressure_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::yesense_interface::msg::dds_::Pressure_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.val_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::yesense_interface::msg::dds_::Pressure_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::Pressure_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_PRESSURE__HPP
