/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: RemoteControlChange_.idl
  Source: RemoteControlChange_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_REMOTECONTROLCHANGE__HPP
#define DDSCXX_REMOTECONTROLCHANGE__HPP

#include <string>

namespace robot_msgs
{
namespace msg
{
namespace dds_
{
class RemoteControlChange_
{
private:
 std::string key__;
 std::string val__;

public:
  RemoteControlChange_() = default;

  explicit RemoteControlChange_(
    const std::string& key_,
    const std::string& val_) :
    key__(key_),
    val__(val_) { }

  const std::string& key_() const { return this->key__; }
  std::string& key_() { return this->key__; }
  void key_(const std::string& _val_) { this->key__ = _val_; }
  void key_(std::string&& _val_) { this->key__ = _val_; }
  const std::string& val_() const { return this->val__; }
  std::string& val_() { return this->val__; }
  void val_(const std::string& _val_) { this->val__ = _val_; }
  void val_(std::string&& _val_) { this->val__ = _val_; }

  bool operator==(const RemoteControlChange_& _other) const
  {
    (void) _other;
    return key__ == _other.key__ &&
      val__ == _other.val__;
  }

  bool operator!=(const RemoteControlChange_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::robot_msgs::msg::dds_::RemoteControlChange_>::getTypeName()
{
  return "robot_msgs::msg::dds_::RemoteControlChange_";
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::RemoteControlChange_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::RemoteControlChange_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::RemoteControlChange_>::type_map_blob_sz() { return 262; }
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::RemoteControlChange_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::RemoteControlChange_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x4c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x3e,  0x13,  0x36,  0x11,  0xef,  0x61,  0xe7, 
 0xe4,  0x9a,  0x09,  0x0b,  0xb4,  0x8a,  0x7e,  0x00,  0x34,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0xb9,  0xbd,  0xf9,  0x68, 
 0x0c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0xd7,  0x1f,  0xe6,  0x5d, 
 0x8b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x6b,  0xf1,  0xd1,  0x6d,  0x3f,  0xe3,  0x47, 
 0x48,  0x60,  0x8e,  0x33,  0x00,  0x1c,  0xce,  0x00,  0x73,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x34,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x2c,  0x00,  0x00,  0x00,  0x72,  0x6f,  0x62,  0x6f, 
 0x74,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73, 
 0x5f,  0x3a,  0x3a,  0x52,  0x65,  0x6d,  0x6f,  0x74,  0x65,  0x43,  0x6f,  0x6e,  0x74,  0x72,  0x6f,  0x6c, 
 0x43,  0x68,  0x61,  0x6e,  0x67,  0x65,  0x5f,  0x00,  0x33,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x13,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x6b,  0x65,  0x79,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x70,  0x00,  0x05,  0x00,  0x00,  0x00,  0x76,  0x61,  0x6c,  0x5f,  0x00,  0x00,  0x00,  0x00, 
 0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x6b,  0xf1,  0xd1,  0x6d,  0x3f,  0xe3,  0x47, 
 0x48,  0x60,  0x8e,  0x33,  0x00,  0x1c,  0xce,  0xf1,  0x3e,  0x13,  0x36,  0x11,  0xef,  0x61,  0xe7,  0xe4, 
 0x9a,  0x09,  0x0b,  0xb4,  0x8a,  0x7e, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::RemoteControlChange_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x3e,  0x13,  0x36,  0x11,  0xef,  0x61,  0xe7,  0xe4,  0x9a,  0x09,  0x0b, 
 0xb4,  0x8a,  0x7e,  0x00,  0x38,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x6b,  0xf1,  0xd1,  0x6d,  0x3f,  0xe3,  0x47,  0x48,  0x60,  0x8e,  0x33, 
 0x00,  0x1c,  0xce,  0x00,  0x77,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::robot_msgs::msg::dds_::RemoteControlChange_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::robot_msgs::msg::dds_::RemoteControlChange_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::robot_msgs::msg::dds_::RemoteControlChange_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::robot_msgs::msg::dds_::RemoteControlChange_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::robot_msgs::msg::dds_::RemoteControlChange_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.key_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.val_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::robot_msgs::msg::dds_::RemoteControlChange_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::RemoteControlChange_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::robot_msgs::msg::dds_::RemoteControlChange_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.key_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.val_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::robot_msgs::msg::dds_::RemoteControlChange_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::RemoteControlChange_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::robot_msgs::msg::dds_::RemoteControlChange_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.key_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.val_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::robot_msgs::msg::dds_::RemoteControlChange_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::RemoteControlChange_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::robot_msgs::msg::dds_::RemoteControlChange_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.key_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.val_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::robot_msgs::msg::dds_::RemoteControlChange_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::RemoteControlChange_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_REMOTECONTROLCHANGE__HPP
