/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: RemoteControlHead_.idl
  Source: RemoteControlHead_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_REMOTECONTROLHEAD__HPP
#define DDSCXX_REMOTECONTROLHEAD__HPP


namespace robot_msgs
{
namespace msg
{
namespace dds_
{
class RemoteControlHead_
{
private:
 float pos_roll__ = 0.0f;
 float pos_pitch__ = 0.0f;
 bool is_absolute__ = false;

public:
  RemoteControlHead_() = default;

  explicit RemoteControlHead_(
    float pos_roll_,
    float pos_pitch_,
    bool is_absolute_) :
    pos_roll__(pos_roll_),
    pos_pitch__(pos_pitch_),
    is_absolute__(is_absolute_) { }

  float pos_roll_() const { return this->pos_roll__; }
  float& pos_roll_() { return this->pos_roll__; }
  void pos_roll_(float _val_) { this->pos_roll__ = _val_; }
  float pos_pitch_() const { return this->pos_pitch__; }
  float& pos_pitch_() { return this->pos_pitch__; }
  void pos_pitch_(float _val_) { this->pos_pitch__ = _val_; }
  bool is_absolute_() const { return this->is_absolute__; }
  bool& is_absolute_() { return this->is_absolute__; }
  void is_absolute_(bool _val_) { this->is_absolute__ = _val_; }

  bool operator==(const RemoteControlHead_& _other) const
  {
    (void) _other;
    return pos_roll__ == _other.pos_roll__ &&
      pos_pitch__ == _other.pos_pitch__ &&
      is_absolute__ == _other.is_absolute__;
  }

  bool operator!=(const RemoteControlHead_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::robot_msgs::msg::dds_::RemoteControlHead_>::getTypeName()
{
  return "robot_msgs::msg::dds_::RemoteControlHead_";
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::RemoteControlHead_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::RemoteControlHead_>::type_map_blob_sz() { return 322; }
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::RemoteControlHead_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::RemoteControlHead_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x5b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x9b,  0xa8,  0x09,  0x40,  0x94,  0xe6,  0x09, 
 0xa0,  0x9e,  0x27,  0x94,  0xa2,  0x89,  0x4a,  0x00,  0x43,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x33,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x28,  0x51,  0x1b,  0x07,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x6f,  0xf8,  0x50,  0x35,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0xe4,  0x2b,  0xba,  0x5f,  0x00, 
 0xb7,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x7e,  0x73,  0xcd,  0xf1,  0x5f,  0x41,  0x65, 
 0x33,  0x6f,  0xbd,  0x1c,  0x98,  0x69,  0x48,  0x00,  0x9f,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x32,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x2a,  0x00,  0x00,  0x00,  0x72,  0x6f,  0x62,  0x6f, 
 0x74,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73, 
 0x5f,  0x3a,  0x3a,  0x52,  0x65,  0x6d,  0x6f,  0x74,  0x65,  0x43,  0x6f,  0x6e,  0x74,  0x72,  0x6f,  0x6c, 
 0x48,  0x65,  0x61,  0x64,  0x5f,  0x00,  0x00,  0x00,  0x5f,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x18,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x0a,  0x00,  0x00,  0x00, 
 0x70,  0x6f,  0x73,  0x5f,  0x72,  0x6f,  0x6c,  0x6c,  0x5f,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x70,  0x6f,  0x73,  0x5f, 
 0x70,  0x69,  0x74,  0x63,  0x68,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1b,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x00,  0x0d,  0x00,  0x00,  0x00,  0x69,  0x73,  0x5f,  0x61, 
 0x62,  0x73,  0x6f,  0x6c,  0x75,  0x74,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0xf2,  0x7e,  0x73,  0xcd,  0xf1,  0x5f,  0x41,  0x65,  0x33,  0x6f,  0xbd,  0x1c, 
 0x98,  0x69,  0x48,  0xf1,  0x9b,  0xa8,  0x09,  0x40,  0x94,  0xe6,  0x09,  0xa0,  0x9e,  0x27,  0x94,  0xa2, 
 0x89,  0x4a, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::RemoteControlHead_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x9b,  0xa8,  0x09,  0x40,  0x94,  0xe6,  0x09,  0xa0,  0x9e,  0x27,  0x94, 
 0xa2,  0x89,  0x4a,  0x00,  0x47,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x7e,  0x73,  0xcd,  0xf1,  0x5f,  0x41,  0x65,  0x33,  0x6f,  0xbd,  0x1c, 
 0x98,  0x69,  0x48,  0x00,  0xa3,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::robot_msgs::msg::dds_::RemoteControlHead_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::robot_msgs::msg::dds_::RemoteControlHead_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::robot_msgs::msg::dds_::RemoteControlHead_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::robot_msgs::msg::dds_::RemoteControlHead_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::robot_msgs::msg::dds_::RemoteControlHead_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.pos_roll_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.pos_pitch_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.is_absolute_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::robot_msgs::msg::dds_::RemoteControlHead_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::RemoteControlHead_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::robot_msgs::msg::dds_::RemoteControlHead_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.pos_roll_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.pos_pitch_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.is_absolute_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::robot_msgs::msg::dds_::RemoteControlHead_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::RemoteControlHead_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::robot_msgs::msg::dds_::RemoteControlHead_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.pos_roll_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.pos_pitch_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.is_absolute_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::robot_msgs::msg::dds_::RemoteControlHead_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::RemoteControlHead_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::robot_msgs::msg::dds_::RemoteControlHead_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.pos_roll_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.pos_pitch_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.is_absolute_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::robot_msgs::msg::dds_::RemoteControlHead_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::RemoteControlHead_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_REMOTECONTROLHEAD__HPP
