/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: SampleTimestamp_.idl
  Source: SampleTimestamp_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_SAMPLETIMESTAMP__HPP
#define DDSCXX_SAMPLETIMESTAMP__HPP

#include <cstdint>

namespace yesense_interface
{
namespace msg
{
namespace dds_
{
class SampleTimestamp_
{
private:
 uint32_t timestamp__ = 0;

public:
  SampleTimestamp_() = default;

  explicit SampleTimestamp_(
    uint32_t timestamp_) :
    timestamp__(timestamp_) { }

  uint32_t timestamp_() const { return this->timestamp__; }
  uint32_t& timestamp_() { return this->timestamp__; }
  void timestamp_(uint32_t _val_) { this->timestamp__ = _val_; }

  bool operator==(const SampleTimestamp_& _other) const
  {
    (void) _other;
    return timestamp__ == _other.timestamp__;
  }

  bool operator!=(const SampleTimestamp_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::yesense_interface::msg::dds_::SampleTimestamp_>::getTypeName()
{
  return "yesense_interface::msg::dds_::SampleTimestamp_";
}

template <> constexpr bool TopicTraits<::yesense_interface::msg::dds_::SampleTimestamp_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::SampleTimestamp_>::type_map_blob_sz() { return 234; }
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::SampleTimestamp_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::SampleTimestamp_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x3b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xea,  0x15,  0x3b,  0x66,  0x19,  0x2f,  0x78, 
 0x87,  0xa2,  0xf4,  0x13,  0xfd,  0x5b,  0x66,  0x00,  0x23,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0xee,  0x0a,  0x2c,  0x82,  0x00, 
 0x7d,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xe2,  0xba,  0xdf,  0xd0,  0x1d,  0x1d,  0xb6, 
 0x97,  0xa2,  0x6c,  0x30,  0xad,  0xc5,  0x21,  0x00,  0x65,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x37,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x2f,  0x00,  0x00,  0x00,  0x79,  0x65,  0x73,  0x65, 
 0x6e,  0x73,  0x65,  0x5f,  0x69,  0x6e,  0x74,  0x65,  0x72,  0x66,  0x61,  0x63,  0x65,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x53,  0x61,  0x6d,  0x70,  0x6c,  0x65, 
 0x54,  0x69,  0x6d,  0x65,  0x73,  0x74,  0x61,  0x6d,  0x70,  0x5f,  0x00,  0x00,  0x21,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x74,  0x69,  0x6d,  0x65,  0x73,  0x74,  0x61,  0x6d,  0x70,  0x5f,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xe2,  0xba,  0xdf, 
 0xd0,  0x1d,  0x1d,  0xb6,  0x97,  0xa2,  0x6c,  0x30,  0xad,  0xc5,  0x21,  0xf1,  0xea,  0x15,  0x3b,  0x66, 
 0x19,  0x2f,  0x78,  0x87,  0xa2,  0xf4,  0x13,  0xfd,  0x5b,  0x66, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::SampleTimestamp_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xea,  0x15,  0x3b,  0x66,  0x19,  0x2f,  0x78,  0x87,  0xa2,  0xf4,  0x13, 
 0xfd,  0x5b,  0x66,  0x00,  0x27,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xe2,  0xba,  0xdf,  0xd0,  0x1d,  0x1d,  0xb6,  0x97,  0xa2,  0x6c,  0x30, 
 0xad,  0xc5,  0x21,  0x00,  0x69,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::yesense_interface::msg::dds_::SampleTimestamp_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::yesense_interface::msg::dds_::SampleTimestamp_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::yesense_interface::msg::dds_::SampleTimestamp_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::yesense_interface::msg::dds_::SampleTimestamp_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::yesense_interface::msg::dds_::SampleTimestamp_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.timestamp_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::yesense_interface::msg::dds_::SampleTimestamp_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::SampleTimestamp_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::yesense_interface::msg::dds_::SampleTimestamp_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.timestamp_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::yesense_interface::msg::dds_::SampleTimestamp_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::SampleTimestamp_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::yesense_interface::msg::dds_::SampleTimestamp_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.timestamp_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::yesense_interface::msg::dds_::SampleTimestamp_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::SampleTimestamp_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::yesense_interface::msg::dds_::SampleTimestamp_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.timestamp_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::yesense_interface::msg::dds_::SampleTimestamp_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::SampleTimestamp_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_SAMPLETIMESTAMP__HPP
