/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: SpeakStatus_.idl
  Source: SpeakStatus_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_SPEAKSTATUS__HPP
#define DDSCXX_SPEAKSTATUS__HPP

#include <cstdint>
#include <string>

namespace robot_msgs
{
namespace msg
{
namespace dds_
{
namespace SpeakStatus_Constants
{
const uint8_t STATE_IDLE_ = 0;

const uint8_t STATE_PLAYING_ = 1;

const uint8_t STATE_PAUSED_ = 2;

}

class SpeakStatus_
{
private:
 uint8_t status__ = 0;
 std::string current_text__;
 uint8_t queue_size__ = 0;

public:
  SpeakStatus_() = default;

  explicit SpeakStatus_(
    uint8_t status_,
    const std::string& current_text_,
    uint8_t queue_size_) :
    status__(status_),
    current_text__(current_text_),
    queue_size__(queue_size_) { }

  uint8_t status_() const { return this->status__; }
  uint8_t& status_() { return this->status__; }
  void status_(uint8_t _val_) { this->status__ = _val_; }
  const std::string& current_text_() const { return this->current_text__; }
  std::string& current_text_() { return this->current_text__; }
  void current_text_(const std::string& _val_) { this->current_text__ = _val_; }
  void current_text_(std::string&& _val_) { this->current_text__ = _val_; }
  uint8_t queue_size_() const { return this->queue_size__; }
  uint8_t& queue_size_() { return this->queue_size__; }
  void queue_size_(uint8_t _val_) { this->queue_size__ = _val_; }

  bool operator==(const SpeakStatus_& _other) const
  {
    (void) _other;
    return status__ == _other.status__ &&
      current_text__ == _other.current_text__ &&
      queue_size__ == _other.queue_size__;
  }

  bool operator!=(const SpeakStatus_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::robot_msgs::msg::dds_::SpeakStatus_>::getTypeName()
{
  return "robot_msgs::msg::dds_::SpeakStatus_";
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::SpeakStatus_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::SpeakStatus_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::SpeakStatus_>::type_map_blob_sz() { return 314; }
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::SpeakStatus_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::SpeakStatus_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x5b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xc5,  0x27,  0xfd,  0x2f,  0x70,  0xcd,  0xf0, 
 0x46,  0xa5,  0x7d,  0xe5,  0xa5,  0xa0,  0x29,  0x00,  0x43,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x33,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x15,  0x80,  0x29,  0x11,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0xe6,  0x85,  0x0f,  0x0e, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0xa5,  0xfe,  0x8c,  0xc8,  0x00, 
 0xae,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xb3,  0xc5,  0x40,  0x02,  0xb2,  0xa1,  0x4f, 
 0xa2,  0x08,  0x7c,  0x19,  0xe2,  0xc4,  0x32,  0x00,  0x96,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x2c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00,  0x72,  0x6f,  0x62,  0x6f, 
 0x74,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73, 
 0x5f,  0x3a,  0x3a,  0x53,  0x70,  0x65,  0x61,  0x6b,  0x53,  0x74,  0x61,  0x74,  0x75,  0x73,  0x5f,  0x00, 
 0x5e,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x02,  0x00,  0x08,  0x00,  0x00,  0x00,  0x73,  0x74,  0x61,  0x74,  0x75,  0x73,  0x5f,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00, 
 0x0e,  0x00,  0x00,  0x00,  0x63,  0x75,  0x72,  0x72,  0x65,  0x6e,  0x74,  0x5f,  0x74,  0x65,  0x78,  0x74, 
 0x5f,  0x00,  0x00,  0x00,  0x1a,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x71,  0x75,  0x65,  0x75,  0x65,  0x5f,  0x73,  0x69,  0x7a,  0x65,  0x5f,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xb3,  0xc5,  0x40, 
 0x02,  0xb2,  0xa1,  0x4f,  0xa2,  0x08,  0x7c,  0x19,  0xe2,  0xc4,  0x32,  0xf1,  0xc5,  0x27,  0xfd,  0x2f, 
 0x70,  0xcd,  0xf0,  0x46,  0xa5,  0x7d,  0xe5,  0xa5,  0xa0,  0x29, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::SpeakStatus_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xc5,  0x27,  0xfd,  0x2f,  0x70,  0xcd,  0xf0,  0x46,  0xa5,  0x7d,  0xe5, 
 0xa5,  0xa0,  0x29,  0x00,  0x47,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xb3,  0xc5,  0x40,  0x02,  0xb2,  0xa1,  0x4f,  0xa2,  0x08,  0x7c,  0x19, 
 0xe2,  0xc4,  0x32,  0x00,  0x9a,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::robot_msgs::msg::dds_::SpeakStatus_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::robot_msgs::msg::dds_::SpeakStatus_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::robot_msgs::msg::dds_::SpeakStatus_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::robot_msgs::msg::dds_::SpeakStatus_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::robot_msgs::msg::dds_::SpeakStatus_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.status_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.current_text_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.queue_size_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::robot_msgs::msg::dds_::SpeakStatus_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::SpeakStatus_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::robot_msgs::msg::dds_::SpeakStatus_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.status_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.current_text_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.queue_size_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::robot_msgs::msg::dds_::SpeakStatus_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::SpeakStatus_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::robot_msgs::msg::dds_::SpeakStatus_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.status_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.current_text_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.queue_size_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::robot_msgs::msg::dds_::SpeakStatus_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::SpeakStatus_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::robot_msgs::msg::dds_::SpeakStatus_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.status_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.current_text_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.queue_size_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::robot_msgs::msg::dds_::SpeakStatus_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::SpeakStatus_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_SPEAKSTATUS__HPP
