/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: Utc_.idl
  Source: Utc_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_UTC__HPP
#define DDSCXX_UTC__HPP

#include <cstdint>

namespace yesense_interface
{
namespace msg
{
namespace dds_
{
class Utc_
{
private:
 uint16_t year__ = 0;
 uint8_t month__ = 0;
 uint8_t day__ = 0;
 uint8_t hour__ = 0;
 uint8_t min__ = 0;
 uint8_t sec__ = 0;
 uint32_t ms__ = 0;

public:
  Utc_() = default;

  explicit Utc_(
    uint16_t year_,
    uint8_t month_,
    uint8_t day_,
    uint8_t hour_,
    uint8_t min_,
    uint8_t sec_,
    uint32_t ms_) :
    year__(year_),
    month__(month_),
    day__(day_),
    hour__(hour_),
    min__(min_),
    sec__(sec_),
    ms__(ms_) { }

  uint16_t year_() const { return this->year__; }
  uint16_t& year_() { return this->year__; }
  void year_(uint16_t _val_) { this->year__ = _val_; }
  uint8_t month_() const { return this->month__; }
  uint8_t& month_() { return this->month__; }
  void month_(uint8_t _val_) { this->month__ = _val_; }
  uint8_t day_() const { return this->day__; }
  uint8_t& day_() { return this->day__; }
  void day_(uint8_t _val_) { this->day__ = _val_; }
  uint8_t hour_() const { return this->hour__; }
  uint8_t& hour_() { return this->hour__; }
  void hour_(uint8_t _val_) { this->hour__ = _val_; }
  uint8_t min_() const { return this->min__; }
  uint8_t& min_() { return this->min__; }
  void min_(uint8_t _val_) { this->min__ = _val_; }
  uint8_t sec_() const { return this->sec__; }
  uint8_t& sec_() { return this->sec__; }
  void sec_(uint8_t _val_) { this->sec__ = _val_; }
  uint32_t ms_() const { return this->ms__; }
  uint32_t& ms_() { return this->ms__; }
  void ms_(uint32_t _val_) { this->ms__ = _val_; }

  bool operator==(const Utc_& _other) const
  {
    (void) _other;
    return year__ == _other.year__ &&
      month__ == _other.month__ &&
      day__ == _other.day__ &&
      hour__ == _other.hour__ &&
      min__ == _other.min__ &&
      sec__ == _other.sec__ &&
      ms__ == _other.ms__;
  }

  bool operator!=(const Utc_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::yesense_interface::msg::dds_::Utc_>::getTypeName()
{
  return "yesense_interface::msg::dds_::Utc_";
}

template <> constexpr bool TopicTraits<::yesense_interface::msg::dds_::Utc_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::Utc_>::type_map_blob_sz() { return 458; }
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::Utc_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::Utc_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x9b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x6a,  0xe4,  0x4b,  0xba,  0x07,  0x84,  0xda, 
 0xfd,  0x26,  0x28,  0x05,  0x75,  0x84,  0x3d,  0x00,  0x83,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x73,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x06,  0x6d,  0xb3,  0xe0,  0x8b,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0xb4,  0x6c,  0x56,  0xd0,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x86,  0x10,  0xbc,  0xb6,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x57,  0x0d,  0x42,  0xf8,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x5b,  0x86,  0xc2,  0xa4,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x0b,  0x39,  0x9b,  0x59,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x48,  0xa6,  0x3a,  0x24,  0x00, 
 0xfe,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x5a,  0xb7,  0x01,  0x6b,  0x69,  0x94,  0x12, 
 0x14,  0xed,  0x12,  0x87,  0x5f,  0x24,  0x86,  0x00,  0xe6,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x2b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x23,  0x00,  0x00,  0x00,  0x79,  0x65,  0x73,  0x65, 
 0x6e,  0x73,  0x65,  0x5f,  0x69,  0x6e,  0x74,  0x65,  0x72,  0x66,  0x61,  0x63,  0x65,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x55,  0x74,  0x63,  0x5f,  0x00,  0x00, 
 0xae,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x06,  0x00,  0x06,  0x00,  0x00,  0x00,  0x79,  0x65,  0x61,  0x72,  0x5f,  0x00,  0x00,  0x00, 
 0x15,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00,  0x07,  0x00,  0x00,  0x00, 
 0x6d,  0x6f,  0x6e,  0x74,  0x68,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00,  0x05,  0x00,  0x00,  0x00,  0x64,  0x61,  0x79,  0x5f, 
 0x00,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00, 
 0x06,  0x00,  0x00,  0x00,  0x68,  0x6f,  0x75,  0x72,  0x5f,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00, 
 0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00,  0x05,  0x00,  0x00,  0x00,  0x6d,  0x69,  0x6e,  0x5f, 
 0x00,  0x00,  0x00,  0x00,  0x13,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x73,  0x65,  0x63,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x12,  0x00,  0x00,  0x00, 
 0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x04,  0x00,  0x00,  0x00,  0x6d,  0x73,  0x5f,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x5a,  0xb7,  0x01, 
 0x6b,  0x69,  0x94,  0x12,  0x14,  0xed,  0x12,  0x87,  0x5f,  0x24,  0x86,  0xf1,  0x6a,  0xe4,  0x4b,  0xba, 
 0x07,  0x84,  0xda,  0xfd,  0x26,  0x28,  0x05,  0x75,  0x84,  0x3d, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::Utc_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x6a,  0xe4,  0x4b,  0xba,  0x07,  0x84,  0xda,  0xfd,  0x26,  0x28,  0x05, 
 0x75,  0x84,  0x3d,  0x00,  0x87,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x5a,  0xb7,  0x01,  0x6b,  0x69,  0x94,  0x12,  0x14,  0xed,  0x12,  0x87, 
 0x5f,  0x24,  0x86,  0x00,  0xea,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::yesense_interface::msg::dds_::Utc_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::yesense_interface::msg::dds_::Utc_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::yesense_interface::msg::dds_::Utc_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::yesense_interface::msg::dds_::Utc_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::yesense_interface::msg::dds_::Utc_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.year_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.month_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.day_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.hour_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.min_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.sec_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.ms_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::yesense_interface::msg::dds_::Utc_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::Utc_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::yesense_interface::msg::dds_::Utc_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.year_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.month_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.day_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.hour_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.min_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.sec_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.ms_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::yesense_interface::msg::dds_::Utc_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::Utc_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::yesense_interface::msg::dds_::Utc_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.year_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.month_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.day_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.hour_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.min_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.sec_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.ms_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::yesense_interface::msg::dds_::Utc_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::Utc_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::yesense_interface::msg::dds_::Utc_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.year_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.month_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.day_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.hour_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.min_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.sec_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.ms_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::yesense_interface::msg::dds_::Utc_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::Utc_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_UTC__HPP
