/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: Vel_.idl
  Source: Vel_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_VEL__HPP
#define DDSCXX_VEL__HPP


namespace yesense_interface
{
namespace msg
{
namespace dds_
{
class Vel_
{
private:
 float vel_e__ = 0.0f;
 float vel_n__ = 0.0f;
 float vel_u__ = 0.0f;

public:
  Vel_() = default;

  explicit Vel_(
    float vel_e_,
    float vel_n_,
    float vel_u_) :
    vel_e__(vel_e_),
    vel_n__(vel_n_),
    vel_u__(vel_u_) { }

  float vel_e_() const { return this->vel_e__; }
  float& vel_e_() { return this->vel_e__; }
  void vel_e_(float _val_) { this->vel_e__ = _val_; }
  float vel_n_() const { return this->vel_n__; }
  float& vel_n_() { return this->vel_n__; }
  void vel_n_(float _val_) { this->vel_n__ = _val_; }
  float vel_u_() const { return this->vel_u__; }
  float& vel_u_() { return this->vel_u__; }
  void vel_u_(float _val_) { this->vel_u__ = _val_; }

  bool operator==(const Vel_& _other) const
  {
    (void) _other;
    return vel_e__ == _other.vel_e__ &&
      vel_n__ == _other.vel_n__ &&
      vel_u__ == _other.vel_u__;
  }

  bool operator!=(const Vel_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::yesense_interface::msg::dds_::Vel_>::getTypeName()
{
  return "yesense_interface::msg::dds_::Vel_";
}

template <> constexpr bool TopicTraits<::yesense_interface::msg::dds_::Vel_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::Vel_>::type_map_blob_sz() { return 306; }
template<> constexpr unsigned int TopicTraits<::yesense_interface::msg::dds_::Vel_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::Vel_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x5b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x5a,  0x78,  0x69,  0x9c,  0xd7,  0x56,  0x60, 
 0x01,  0x4d,  0x07,  0x2b,  0x59,  0x63,  0x5d,  0x00,  0x43,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x33,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xe0,  0xb4,  0xec,  0x66,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xbb,  0xb4,  0xae,  0xb2,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xfc,  0x45,  0xd9,  0x8c,  0x00, 
 0xa5,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x5e,  0x51,  0x01,  0xed,  0x3f,  0x54,  0xab, 
 0x77,  0x7b,  0xb0,  0x80,  0x42,  0x5c,  0xca,  0x00,  0x8d,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x2b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x23,  0x00,  0x00,  0x00,  0x79,  0x65,  0x73,  0x65, 
 0x6e,  0x73,  0x65,  0x5f,  0x69,  0x6e,  0x74,  0x65,  0x72,  0x66,  0x61,  0x63,  0x65,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x56,  0x65,  0x6c,  0x5f,  0x00,  0x00, 
 0x55,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x07,  0x00,  0x00,  0x00,  0x76,  0x65,  0x6c,  0x5f,  0x65,  0x5f,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00, 
 0x07,  0x00,  0x00,  0x00,  0x76,  0x65,  0x6c,  0x5f,  0x6e,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x15,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x07,  0x00,  0x00,  0x00, 
 0x76,  0x65,  0x6c,  0x5f,  0x75,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0xf2,  0x5e,  0x51,  0x01,  0xed,  0x3f,  0x54,  0xab,  0x77,  0x7b,  0xb0,  0x80, 
 0x42,  0x5c,  0xca,  0xf1,  0x5a,  0x78,  0x69,  0x9c,  0xd7,  0x56,  0x60,  0x01,  0x4d,  0x07,  0x2b,  0x59, 
 0x63,  0x5d, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::yesense_interface::msg::dds_::Vel_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x5a,  0x78,  0x69,  0x9c,  0xd7,  0x56,  0x60,  0x01,  0x4d,  0x07,  0x2b, 
 0x59,  0x63,  0x5d,  0x00,  0x47,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x5e,  0x51,  0x01,  0xed,  0x3f,  0x54,  0xab,  0x77,  0x7b,  0xb0,  0x80, 
 0x42,  0x5c,  0xca,  0x00,  0x91,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::yesense_interface::msg::dds_::Vel_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::yesense_interface::msg::dds_::Vel_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::yesense_interface::msg::dds_::Vel_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::yesense_interface::msg::dds_::Vel_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::yesense_interface::msg::dds_::Vel_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.vel_e_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.vel_n_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.vel_u_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::yesense_interface::msg::dds_::Vel_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::Vel_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::yesense_interface::msg::dds_::Vel_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.vel_e_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.vel_n_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.vel_u_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::yesense_interface::msg::dds_::Vel_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::Vel_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::yesense_interface::msg::dds_::Vel_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.vel_e_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.vel_n_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.vel_u_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::yesense_interface::msg::dds_::Vel_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::Vel_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::yesense_interface::msg::dds_::Vel_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.vel_e_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.vel_n_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.vel_u_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::yesense_interface::msg::dds_::Vel_& instance, bool as_key) {
  auto &props = get_type_props<::yesense_interface::msg::dds_::Vel_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_VEL__HPP
