/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: VoiceText_.idl
  Source: VoiceText_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_VOICETEXT__HPP
#define DDSCXX_VOICETEXT__HPP

#include <cstdint>
#include <string>

namespace robot_msgs
{
namespace msg
{
namespace dds_
{
class VoiceText_
{
private:
 std::string text__;
 uint8_t priority__ = 0;

public:
  VoiceText_() = default;

  explicit VoiceText_(
    const std::string& text_,
    uint8_t priority_) :
    text__(text_),
    priority__(priority_) { }

  const std::string& text_() const { return this->text__; }
  std::string& text_() { return this->text__; }
  void text_(const std::string& _val_) { this->text__ = _val_; }
  void text_(std::string&& _val_) { this->text__ = _val_; }
  uint8_t priority_() const { return this->priority__; }
  uint8_t& priority_() { return this->priority__; }
  void priority_(uint8_t _val_) { this->priority__ = _val_; }

  bool operator==(const VoiceText_& _other) const
  {
    (void) _other;
    return text__ == _other.text__ &&
      priority__ == _other.priority__;
  }

  bool operator!=(const VoiceText_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::robot_msgs::msg::dds_::VoiceText_>::getTypeName()
{
  return "robot_msgs::msg::dds_::VoiceText_";
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::VoiceText_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::VoiceText_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::VoiceText_>::type_map_blob_sz() { return 258; }
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::VoiceText_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::VoiceText_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x4b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xd6,  0xe5,  0x68,  0x62,  0x12,  0x3c,  0xb1, 
 0x5d,  0x10,  0x9a,  0x07,  0x1f,  0xeb,  0x61,  0x00,  0x33,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x23,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0xd8,  0xc4,  0xed,  0x57, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0xc0,  0xae,  0x7f,  0x00,  0x00, 
 0x88,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x3f,  0x60,  0xed,  0x02,  0x3a,  0x03,  0x88, 
 0xbb,  0xc4,  0xa3,  0x1c,  0xc4,  0x55,  0xca,  0x00,  0x70,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x2a,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x72,  0x6f,  0x62,  0x6f, 
 0x74,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73, 
 0x5f,  0x3a,  0x3a,  0x56,  0x6f,  0x69,  0x63,  0x65,  0x54,  0x65,  0x78,  0x74,  0x5f,  0x00,  0x00,  0x00, 
 0x38,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x70,  0x00,  0x06,  0x00,  0x00,  0x00,  0x74,  0x65,  0x78,  0x74,  0x5f,  0x00,  0x00,  0x00, 
 0x18,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x02,  0x00,  0x0a,  0x00,  0x00,  0x00, 
 0x70,  0x72,  0x69,  0x6f,  0x72,  0x69,  0x74,  0x79,  0x5f,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0xf2,  0x3f,  0x60,  0xed,  0x02,  0x3a,  0x03,  0x88,  0xbb,  0xc4,  0xa3,  0x1c, 
 0xc4,  0x55,  0xca,  0xf1,  0xd6,  0xe5,  0x68,  0x62,  0x12,  0x3c,  0xb1,  0x5d,  0x10,  0x9a,  0x07,  0x1f, 
 0xeb,  0x61, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::VoiceText_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xd6,  0xe5,  0x68,  0x62,  0x12,  0x3c,  0xb1,  0x5d,  0x10,  0x9a,  0x07, 
 0x1f,  0xeb,  0x61,  0x00,  0x37,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x3f,  0x60,  0xed,  0x02,  0x3a,  0x03,  0x88,  0xbb,  0xc4,  0xa3,  0x1c, 
 0xc4,  0x55,  0xca,  0x00,  0x74,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::robot_msgs::msg::dds_::VoiceText_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::robot_msgs::msg::dds_::VoiceText_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::robot_msgs::msg::dds_::VoiceText_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::robot_msgs::msg::dds_::VoiceText_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::robot_msgs::msg::dds_::VoiceText_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.text_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.priority_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::robot_msgs::msg::dds_::VoiceText_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::VoiceText_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::robot_msgs::msg::dds_::VoiceText_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.text_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.priority_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::robot_msgs::msg::dds_::VoiceText_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::VoiceText_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::robot_msgs::msg::dds_::VoiceText_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.text_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.priority_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::robot_msgs::msg::dds_::VoiceText_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::VoiceText_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::robot_msgs::msg::dds_::VoiceText_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.text_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.priority_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::robot_msgs::msg::dds_::VoiceText_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::VoiceText_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_VOICETEXT__HPP
