/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: ZVHeader_.idl
  Source: ZVHeader_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_ZVHEADER__HPP
#define DDSCXX_ZVHEADER__HPP

#include "Time_.hpp"

#include <string>

namespace comm_msgs
{
namespace msg
{
namespace dds_
{
class ZVHeader_
{
private:
 ::builtin_interfaces::msg::dds_::Time_ time__;
 std::string trace_id__;
 std::string reserve__;

public:
  ZVHeader_() = default;

  explicit ZVHeader_(
    const ::builtin_interfaces::msg::dds_::Time_& time_,
    const std::string& trace_id_,
    const std::string& reserve_) :
    time__(time_),
    trace_id__(trace_id_),
    reserve__(reserve_) { }

  const ::builtin_interfaces::msg::dds_::Time_& time_() const { return this->time__; }
  ::builtin_interfaces::msg::dds_::Time_& time_() { return this->time__; }
  void time_(const ::builtin_interfaces::msg::dds_::Time_& _val_) { this->time__ = _val_; }
  void time_(::builtin_interfaces::msg::dds_::Time_&& _val_) { this->time__ = _val_; }
  const std::string& trace_id_() const { return this->trace_id__; }
  std::string& trace_id_() { return this->trace_id__; }
  void trace_id_(const std::string& _val_) { this->trace_id__ = _val_; }
  void trace_id_(std::string&& _val_) { this->trace_id__ = _val_; }
  const std::string& reserve_() const { return this->reserve__; }
  std::string& reserve_() { return this->reserve__; }
  void reserve_(const std::string& _val_) { this->reserve__ = _val_; }
  void reserve_(std::string&& _val_) { this->reserve__ = _val_; }

  bool operator==(const ZVHeader_& _other) const
  {
    (void) _other;
    return time__ == _other.time__ &&
      trace_id__ == _other.trace_id__ &&
      reserve__ == _other.reserve__;
  }

  bool operator!=(const ZVHeader_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::comm_msgs::msg::dds_::ZVHeader_>::getTypeName()
{
  return "comm_msgs::msg::dds_::ZVHeader_";
}

template <> constexpr bool TopicTraits<::comm_msgs::msg::dds_::ZVHeader_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::comm_msgs::msg::dds_::ZVHeader_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::comm_msgs::msg::dds_::ZVHeader_>::type_map_blob_sz() { return 568; }
template<> constexpr unsigned int TopicTraits<::comm_msgs::msg::dds_::ZVHeader_>::type_info_blob_sz() { return 148; }
template<> inline const uint8_t * TopicTraits<::comm_msgs::msg::dds_::ZVHeader_>::type_map_blob() {
  static const uint8_t blob[] = {
 0xb3,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0xf1,  0xc6,  0xa1,  0x08,  0xd2,  0xb6,  0x72,  0x73, 
 0x7b,  0xf5,  0x94,  0xd8,  0x5d,  0x84,  0xbf,  0x00,  0x54,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x44,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0xf1,  0x61,  0x1f,  0xf5,  0xdb,  0x0b, 
 0xf3,  0x3d,  0xd9,  0x7c,  0x4e,  0xfe,  0x81,  0x0a,  0x45,  0xe6,  0x7e,  0x16,  0x70,  0x00,  0x00,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0xbf,  0x88,  0xce,  0x87, 
 0x0c,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0xc3,  0x43,  0x81,  0x66, 
 0xf1,  0x61,  0x1f,  0xf5,  0xdb,  0x0b,  0xf3,  0x3d,  0xd9,  0x7c,  0x4e,  0xfe,  0x81,  0x0a,  0x45,  0x00, 
 0x33,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00,  0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x23,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x04,  0x0b,  0x39,  0x9b,  0x59,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x07,  0xce,  0x1c,  0x29,  0x9a,  0x00,  0x37,  0x01,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0xf2,  0x07,  0xb1,  0x13,  0x02,  0x50,  0x4f,  0xea,  0x69,  0xec,  0xda,  0xe3,  0x35,  0xa6,  0xa4,  0x00, 
 0x97,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x28,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x20,  0x00,  0x00,  0x00,  0x63,  0x6f,  0x6d,  0x6d,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x5a,  0x56,  0x48,  0x65,  0x61,  0x64, 
 0x65,  0x72,  0x5f,  0x00,  0x63,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0xf2,  0x3a,  0x59,  0xec,  0xdf,  0x8b,  0x02,  0x2e,  0x2f,  0x1c, 
 0xf7,  0xec,  0x59,  0x8a,  0xd1,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x74,  0x69,  0x6d,  0x65, 
 0x5f,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00, 
 0x0a,  0x00,  0x00,  0x00,  0x74,  0x72,  0x61,  0x63,  0x65,  0x5f,  0x69,  0x64,  0x5f,  0x00,  0x00,  0x00, 
 0x17,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x09,  0x00,  0x00,  0x00, 
 0x72,  0x65,  0x73,  0x65,  0x72,  0x76,  0x65,  0x5f,  0x00,  0x00,  0x00,  0xf2,  0x3a,  0x59,  0xec,  0xdf, 
 0x8b,  0x02,  0x2e,  0x2f,  0x1c,  0xf7,  0xec,  0x59,  0x8a,  0xd1,  0x00,  0x00,  0x73,  0x00,  0x00,  0x00, 
 0xf2,  0x51,  0x01,  0x00,  0x2d,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x25,  0x00,  0x00,  0x00, 
 0x62,  0x75,  0x69,  0x6c,  0x74,  0x69,  0x6e,  0x5f,  0x69,  0x6e,  0x74,  0x65,  0x72,  0x66,  0x61,  0x63, 
 0x65,  0x73,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x54, 
 0x69,  0x6d,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x37,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x13,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x73,  0x65,  0x63,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x07,  0x00,  0x09,  0x00,  0x00,  0x00,  0x6e,  0x61,  0x6e,  0x6f,  0x73,  0x65,  0x63,  0x5f, 
 0x00,  0x00,  0x00,  0x00,  0x40,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0xf2,  0x07,  0xb1,  0x13, 
 0x02,  0x50,  0x4f,  0xea,  0x69,  0xec,  0xda,  0xe3,  0x35,  0xa6,  0xa4,  0xf1,  0xc6,  0xa1,  0x08,  0xd2, 
 0xb6,  0x72,  0x73,  0x7b,  0xf5,  0x94,  0xd8,  0x5d,  0x84,  0xbf,  0xf2,  0x3a,  0x59,  0xec,  0xdf,  0x8b, 
 0x02,  0x2e,  0x2f,  0x1c,  0xf7,  0xec,  0x59,  0x8a,  0xd1,  0xf1,  0x61,  0x1f,  0xf5,  0xdb,  0x0b,  0xf3, 
 0x3d,  0xd9,  0x7c,  0x4e,  0xfe,  0x81,  0x0a,  0x45, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::comm_msgs::msg::dds_::ZVHeader_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x90,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x40,  0x00,  0x00,  0x00,  0x3c,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xc6,  0xa1,  0x08,  0xd2,  0xb6,  0x72,  0x73,  0x7b,  0xf5,  0x94,  0xd8, 
 0x5d,  0x84,  0xbf,  0x00,  0x58,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf1,  0x61,  0x1f,  0xf5,  0xdb,  0x0b,  0xf3,  0x3d, 
 0xd9,  0x7c,  0x4e,  0xfe,  0x81,  0x0a,  0x45,  0x00,  0x37,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40, 
 0x40,  0x00,  0x00,  0x00,  0x3c,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf2,  0x07,  0xb1,  0x13, 
 0x02,  0x50,  0x4f,  0xea,  0x69,  0xec,  0xda,  0xe3,  0x35,  0xa6,  0xa4,  0x00,  0x9b,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00, 
 0xf2,  0x3a,  0x59,  0xec,  0xdf,  0x8b,  0x02,  0x2e,  0x2f,  0x1c,  0xf7,  0xec,  0x59,  0x8a,  0xd1,  0x00, 
 0x77,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::comm_msgs::msg::dds_::ZVHeader_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::comm_msgs::msg::dds_::ZVHeader_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::comm_msgs::msg::dds_::ZVHeader_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::comm_msgs::msg::dds_::ZVHeader_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::comm_msgs::msg::dds_::ZVHeader_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.time_(), prop))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.trace_id_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.reserve_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::comm_msgs::msg::dds_::ZVHeader_& instance, bool as_key) {
  auto &props = get_type_props<::comm_msgs::msg::dds_::ZVHeader_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::comm_msgs::msg::dds_::ZVHeader_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.time_(), prop))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.trace_id_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.reserve_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::comm_msgs::msg::dds_::ZVHeader_& instance, bool as_key) {
  auto &props = get_type_props<::comm_msgs::msg::dds_::ZVHeader_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::comm_msgs::msg::dds_::ZVHeader_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.time_(), prop))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.trace_id_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.reserve_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::comm_msgs::msg::dds_::ZVHeader_& instance, bool as_key) {
  auto &props = get_type_props<::comm_msgs::msg::dds_::ZVHeader_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::comm_msgs::msg::dds_::ZVHeader_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.time_(), prop))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.trace_id_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.reserve_(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::comm_msgs::msg::dds_::ZVHeader_& instance, bool as_key) {
  auto &props = get_type_props<::comm_msgs::msg::dds_::ZVHeader_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_ZVHEADER__HPP
