"""

        python binding of zv robot sdk
        -----------------------
    
"""
from __future__ import annotations
import collections.abc
import typing
from . import RobotState_Constants
from . import SpeakStatus_Constants
__all__: list[str] = ['AllJointCmd_', 'AllJointState_', 'ArmControl_', 'ArmForce_', 'ArmJointCmd_', 'ArmJointState_', 'ArmState_', 'AttitudeAllData_', 'AttitudeMinAhrs_', 'AttitudeMinVru_', 'ChannelFactory', 'ChannelPublisher_AllJointCmd_', 'ChannelPublisher_String_', 'ChannelSubscriber_AllJointState_', 'ChannelSubscriber_NavAll_', 'ChannelSubscriber_OccupancyGrid_', 'ChannelSubscriber_PoseStamped_', 'ChannelSubscriber_String_', 'CompressedImage_', 'ErrorHistory_', 'ErrorReport_', 'EulerAngle_', 'EulerOnly_', 'GnssPos_', 'HeadControl_', 'HeadJointCmd_', 'HeadJointState_', 'HeadState_', 'Header_', 'Image_', 'ImuDataTenAxis_', 'ImuData_', 'JointCmd_', 'JointState_', 'LegJointCmd_', 'LegJointState_', 'MapMetaData_', 'NavAll_', 'NavMinUtc_', 'NavMin_', 'NavStatus_', 'OccupancyGrid_', 'Point_', 'PosOnly_', 'PoseStamped_', 'Pose_', 'Pressure_', 'Quat_', 'Quaternion_', 'RemoteControlChange_', 'RemoteControlHead_', 'RemoteControlMotion_', 'RobotLord_', 'RobotState_', 'RobotState_Constants', 'SampleTimestamp_', 'SensorTemp_', 'SpeakStatus_', 'SpeakStatus_Constants', 'String_', 'ThreeAxis_', 'Tid_', 'Time_', 'Utc_', 'Vector3_', 'Vel_', 'VoiceText_', 'WaistControl_', 'WaistJointCmd_', 'WaistJointState_', 'WaistState_', 'ZVHeader_']
class AllJointCmd_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: AllJointCmd_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt, index_: typing.SupportsInt, cmd_type_: typing.SupportsInt, joint_cmds_: collections.abc.Sequence[JointCmd_]) -> None:
        ...
    def __ne__(self, arg0: AllJointCmd_) -> bool:
        ...
    @property
    def cmd_type_(self) -> int:
        ...
    @cmd_type_.setter
    def cmd_type_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def index_(self) -> int:
        ...
    @index_.setter
    def index_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_cmds_(self) -> list[JointCmd_]:
        ...
    @joint_cmds_.setter
    def joint_cmds_(self, arg1: collections.abc.Sequence[JointCmd_]) -> None:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
class AllJointState_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: AllJointState_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt, index_: typing.SupportsInt, used_for_ctrl_: typing.SupportsInt, joint_states_: collections.abc.Sequence[JointState_]) -> None:
        ...
    def __ne__(self, arg0: AllJointState_) -> bool:
        ...
    @property
    def index_(self) -> int:
        ...
    @index_.setter
    def index_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_states_(self) -> list[JointState_]:
        ...
    @joint_states_.setter
    def joint_states_(self, arg1: collections.abc.Sequence[JointState_]) -> None:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def used_for_ctrl_(self) -> int:
        ...
    @used_for_ctrl_.setter
    def used_for_ctrl_(self, arg1: typing.SupportsInt) -> None:
        ...
class ArmControl_:
    __hash__: typing.ClassVar[None] = None
    header_: ZVHeader_
    def __eq__(self, arg0: ArmControl_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, header_: ZVHeader_, arm_: typing.SupportsInt, motion_type_: typing.SupportsInt, hand_target_: collections.abc.Sequence[typing.SupportsFloat], arm_target_: collections.abc.Sequence[typing.SupportsFloat], velocity_: typing.SupportsFloat, change_motion_state_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: ArmControl_) -> bool:
        ...
    @property
    def arm_(self) -> int:
        ...
    @arm_.setter
    def arm_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def arm_target_(self) -> list[float]:
        ...
    @arm_target_.setter
    def arm_target_(self, arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
    @property
    def change_motion_state_(self) -> int:
        ...
    @change_motion_state_.setter
    def change_motion_state_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def hand_target_(self) -> list[float]:
        ...
    @hand_target_.setter
    def hand_target_(self, arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
    @property
    def motion_type_(self) -> int:
        ...
    @motion_type_.setter
    def motion_type_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def velocity_(self) -> float:
        ...
    @velocity_.setter
    def velocity_(self, arg1: typing.SupportsFloat) -> None:
        ...
class ArmForce_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: ArmForce_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, force_: collections.abc.Sequence[typing.SupportsFloat], sys_force_: collections.abc.Sequence[typing.SupportsFloat], work_force_: collections.abc.Sequence[typing.SupportsFloat], tool_force_: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
    def __ne__(self, arg0: ArmForce_) -> bool:
        ...
    @property
    def force_(self) -> list[float]:
        ...
    @force_.setter
    def force_(self, arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
    @property
    def sys_force_(self) -> list[float]:
        ...
    @sys_force_.setter
    def sys_force_(self, arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
    @property
    def tool_force_(self) -> list[float]:
        ...
    @tool_force_.setter
    def tool_force_(self, arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
    @property
    def work_force_(self) -> list[float]:
        ...
    @work_force_.setter
    def work_force_(self, arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
class ArmJointCmd_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: ArmJointCmd_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt, index_: typing.SupportsInt, cmd_type_: typing.SupportsInt, joint_cmds_: collections.abc.Sequence[JointCmd_]) -> None:
        ...
    def __ne__(self, arg0: ArmJointCmd_) -> bool:
        ...
    @property
    def cmd_type_(self) -> int:
        ...
    @cmd_type_.setter
    def cmd_type_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def index_(self) -> int:
        ...
    @index_.setter
    def index_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_cmds_(self) -> list[JointCmd_]:
        ...
    @joint_cmds_.setter
    def joint_cmds_(self, arg1: collections.abc.Sequence[JointCmd_]) -> None:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
class ArmJointState_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: ArmJointState_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt, index_: typing.SupportsInt, joint_states_: collections.abc.Sequence[JointState_]) -> None:
        ...
    def __ne__(self, arg0: ArmJointState_) -> bool:
        ...
    @property
    def index_(self) -> int:
        ...
    @index_.setter
    def index_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_states_(self) -> list[JointState_]:
        ...
    @joint_states_.setter
    def joint_states_(self, arg1: collections.abc.Sequence[JointState_]) -> None:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
class ArmState_:
    __hash__: typing.ClassVar[None] = None
    euler_: Vector3_
    fd_: String_
    header_: ZVHeader_
    pose_: Pose_
    def __eq__(self, arg0: ArmState_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, header_: ZVHeader_, joints_: collections.abc.Sequence[typing.SupportsFloat], pose_: Pose_, euler_: Vector3_, dof_: typing.SupportsInt, curr_motion_state_: typing.SupportsInt, fd_: String_) -> None:
        ...
    def __ne__(self, arg0: ArmState_) -> bool:
        ...
    @property
    def curr_motion_state_(self) -> int:
        ...
    @curr_motion_state_.setter
    def curr_motion_state_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def dof_(self) -> int:
        ...
    @dof_.setter
    def dof_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joints_(self) -> list[float]:
        ...
    @joints_.setter
    def joints_(self, arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
class AttitudeAllData_:
    __hash__: typing.ClassVar[None] = None
    att_min_ahrs_: AttitudeMinAhrs_
    quat_: Quat_
    def __eq__(self, arg0: AttitudeAllData_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, att_min_ahrs_: AttitudeMinAhrs_, quat_: Quat_) -> None:
        ...
    def __ne__(self, arg0: AttitudeAllData_) -> bool:
        ...
class AttitudeMinAhrs_:
    __hash__: typing.ClassVar[None] = None
    att_min_vru_: AttitudeMinVru_
    mag_norm_: ThreeAxis_
    mag_raw_: ThreeAxis_
    def __eq__(self, arg0: AttitudeMinAhrs_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, att_min_vru_: AttitudeMinVru_, mag_norm_: ThreeAxis_, mag_raw_: ThreeAxis_) -> None:
        ...
    def __ne__(self, arg0: AttitudeMinAhrs_) -> bool:
        ...
class AttitudeMinVru_:
    __hash__: typing.ClassVar[None] = None
    euler_: EulerAngle_
    imu_basic_: ImuData_
    def __eq__(self, arg0: AttitudeMinVru_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, imu_basic_: ImuData_, euler_: EulerAngle_) -> None:
        ...
    def __ne__(self, arg0: AttitudeMinVru_) -> bool:
        ...
class ChannelFactory:
    @staticmethod
    def Instance() -> ChannelFactory:
        """
                            Get the singleton instance of the channel factory.
                            Note: The returned instance is managed internally and should not be deleted or modified.
        """
    @typing.overload
    def Init(self, domain_id: typing.SupportsInt, network_interface: str = '') -> None:
        ...
    @typing.overload
    def Init(self, json_config_str: str) -> None:
        """
        config in json string
        """
    def Release(self) -> None:
        ...
class ChannelPublisher_AllJointCmd_:
    def CloseChannel(self) -> None:
        ...
    def GetChannelName(self) -> str:
        ...
    def InitChannel(self) -> None:
        ...
    def Write(self, msg: AllJointCmd_, wait_microsec: typing.SupportsInt = 0) -> None:
        ...
    def __init__(self, channel_name: str) -> None:
        ...
class ChannelPublisher_String_:
    def CloseChannel(self) -> None:
        ...
    def GetChannelName(self) -> str:
        ...
    def InitChannel(self) -> None:
        ...
    def Write(self, msg: String_, wait_microsec: typing.SupportsInt = 0) -> None:
        ...
    def __init__(self, channel_name: str) -> None:
        ...
class ChannelSubscriber_AllJointState_:
    def CloseChannel(self) -> None:
        ...
    def GetChannelName(self) -> str:
        ...
    @typing.overload
    def InitChannel(self, handler: collections.abc.Callable, queue_len: typing.SupportsInt = 0) -> None:
        ...
    @typing.overload
    def InitChannel(self) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str, handler: collections.abc.Callable, queue_len: typing.SupportsInt = 0) -> None:
        ...
class ChannelSubscriber_NavAll_:
    def CloseChannel(self) -> None:
        ...
    def GetChannelName(self) -> str:
        ...
    @typing.overload
    def InitChannel(self, handler: collections.abc.Callable, queue_len: typing.SupportsInt = 0) -> None:
        ...
    @typing.overload
    def InitChannel(self) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str, handler: collections.abc.Callable, queue_len: typing.SupportsInt = 0) -> None:
        ...
class ChannelSubscriber_OccupancyGrid_:
    def CloseChannel(self) -> None:
        ...
    def GetChannelName(self) -> str:
        ...
    @typing.overload
    def InitChannel(self, handler: collections.abc.Callable, queue_len: typing.SupportsInt = 0) -> None:
        ...
    @typing.overload
    def InitChannel(self) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str, handler: collections.abc.Callable, queue_len: typing.SupportsInt = 0) -> None:
        ...
class ChannelSubscriber_PoseStamped_:
    def CloseChannel(self) -> None:
        ...
    def GetChannelName(self) -> str:
        ...
    @typing.overload
    def InitChannel(self, handler: collections.abc.Callable, queue_len: typing.SupportsInt = 0) -> None:
        ...
    @typing.overload
    def InitChannel(self) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str, handler: collections.abc.Callable, queue_len: typing.SupportsInt = 0) -> None:
        ...
class ChannelSubscriber_String_:
    def CloseChannel(self) -> None:
        ...
    def GetChannelName(self) -> str:
        ...
    @typing.overload
    def InitChannel(self, handler: collections.abc.Callable, queue_len: typing.SupportsInt = 0) -> None:
        ...
    @typing.overload
    def InitChannel(self) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str) -> None:
        ...
    @typing.overload
    def __init__(self, channel_name: str, handler: collections.abc.Callable, queue_len: typing.SupportsInt = 0) -> None:
        ...
class CompressedImage_:
    __hash__: typing.ClassVar[None] = None
    format_: str
    header_: Header_
    def __eq__(self, arg0: CompressedImage_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, header_: Header_, format_: str, data_: collections.abc.Sequence[typing.SupportsInt]) -> None:
        ...
    def __ne__(self, arg0: CompressedImage_) -> bool:
        ...
    @property
    def data_(self) -> list[int]:
        ...
    @data_.setter
    def data_(self, arg1: collections.abc.Sequence[typing.SupportsInt]) -> None:
        ...
class ErrorHistory_:
    __hash__: typing.ClassVar[None] = None
    error_: ErrorReport_
    timestamp_: Time_
    def __eq__(self, arg0: ErrorHistory_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, error_: ErrorReport_, timestamp_: Time_, count_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: ErrorHistory_) -> bool:
        ...
    @property
    def count_(self) -> int:
        ...
    @count_.setter
    def count_(self, arg1: typing.SupportsInt) -> None:
        ...
class ErrorReport_:
    __hash__: typing.ClassVar[None] = None
    code_: str
    description_: str
    level_: str
    def __eq__(self, arg0: ErrorReport_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, part_: typing.SupportsInt, subpart_: typing.SupportsInt, err_: typing.SupportsInt, level_: str, description_: str, code_: str) -> None:
        ...
    def __ne__(self, arg0: ErrorReport_) -> bool:
        ...
    @property
    def err_(self) -> int:
        ...
    @err_.setter
    def err_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def part_(self) -> int:
        ...
    @part_.setter
    def part_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def subpart_(self) -> int:
        ...
    @subpart_.setter
    def subpart_(self, arg1: typing.SupportsInt) -> None:
        ...
class EulerAngle_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: EulerAngle_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, pitch_: typing.SupportsFloat, roll_: typing.SupportsFloat, yaw_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: EulerAngle_) -> bool:
        ...
    @property
    def pitch_(self) -> float:
        ...
    @pitch_.setter
    def pitch_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def roll_(self) -> float:
        ...
    @roll_.setter
    def roll_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def yaw_(self) -> float:
        ...
    @yaw_.setter
    def yaw_(self, arg1: typing.SupportsFloat) -> None:
        ...
class EulerOnly_:
    __hash__: typing.ClassVar[None] = None
    euler_: EulerAngle_
    tid_: Tid_
    def __eq__(self, arg0: EulerOnly_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, tid_: Tid_, euler_: EulerAngle_) -> None:
        ...
    def __ne__(self, arg0: EulerOnly_) -> bool:
        ...
class GnssPos_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: GnssPos_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, longitude_: typing.SupportsFloat, latitude_: typing.SupportsFloat, altitude_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: GnssPos_) -> bool:
        ...
    @property
    def altitude_(self) -> float:
        ...
    @altitude_.setter
    def altitude_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def latitude_(self) -> float:
        ...
    @latitude_.setter
    def latitude_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def longitude_(self) -> float:
        ...
    @longitude_.setter
    def longitude_(self, arg1: typing.SupportsFloat) -> None:
        ...
class HeadControl_:
    __hash__: typing.ClassVar[None] = None
    header_: ZVHeader_
    def __eq__(self, arg0: HeadControl_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, header_: ZVHeader_, change_motion_state_: typing.SupportsInt, motion_type_: typing.SupportsInt, target_: collections.abc.Sequence[typing.SupportsFloat], velocity_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: HeadControl_) -> bool:
        ...
    @property
    def change_motion_state_(self) -> int:
        ...
    @change_motion_state_.setter
    def change_motion_state_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def motion_type_(self) -> int:
        ...
    @motion_type_.setter
    def motion_type_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def target_(self) -> list[float]:
        ...
    @target_.setter
    def target_(self, arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
    @property
    def velocity_(self) -> float:
        ...
    @velocity_.setter
    def velocity_(self, arg1: typing.SupportsFloat) -> None:
        ...
class HeadJointCmd_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: HeadJointCmd_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt, index_: typing.SupportsInt, cmd_type_: typing.SupportsInt, joint_cmds_: collections.abc.Sequence[JointCmd_]) -> None:
        ...
    def __ne__(self, arg0: HeadJointCmd_) -> bool:
        ...
    @property
    def cmd_type_(self) -> int:
        ...
    @cmd_type_.setter
    def cmd_type_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def index_(self) -> int:
        ...
    @index_.setter
    def index_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_cmds_(self) -> list[JointCmd_]:
        ...
    @joint_cmds_.setter
    def joint_cmds_(self, arg1: collections.abc.Sequence[JointCmd_]) -> None:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
class HeadJointState_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: HeadJointState_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt, index_: typing.SupportsInt, joint_states_: collections.abc.Sequence[JointState_]) -> None:
        ...
    def __ne__(self, arg0: HeadJointState_) -> bool:
        ...
    @property
    def index_(self) -> int:
        ...
    @index_.setter
    def index_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_states_(self) -> list[JointState_]:
        ...
    @joint_states_.setter
    def joint_states_(self, arg1: collections.abc.Sequence[JointState_]) -> None:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
class HeadState_:
    __hash__: typing.ClassVar[None] = None
    euler_: Vector3_
    pose_: Pose_
    def __eq__(self, arg0: HeadState_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, pose_: Pose_, euler_: Vector3_, joints_: collections.abc.Sequence[typing.SupportsFloat], dof_: typing.SupportsInt, curr_motion_state_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: HeadState_) -> bool:
        ...
    @property
    def curr_motion_state_(self) -> int:
        ...
    @curr_motion_state_.setter
    def curr_motion_state_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def dof_(self) -> int:
        ...
    @dof_.setter
    def dof_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joints_(self) -> list[float]:
        ...
    @joints_.setter
    def joints_(self, arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
class Header_:
    __hash__: typing.ClassVar[None] = None
    frame_id_: str
    stamp_: Time_
    def __eq__(self, arg0: Header_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, stamp_: Time_, frame_id_: str) -> None:
        ...
    def __ne__(self, arg0: Header_) -> bool:
        ...
class Image_:
    __hash__: typing.ClassVar[None] = None
    encoding_: str
    header_: Header_
    def __eq__(self, arg0: Image_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, header_: Header_, height_: typing.SupportsInt, width_: typing.SupportsInt, encoding_: str, is_bigendian_: typing.SupportsInt, step_: typing.SupportsInt, data_: collections.abc.Sequence[typing.SupportsInt]) -> None:
        ...
    def __ne__(self, arg0: Image_) -> bool:
        ...
    @property
    def data_(self) -> list[int]:
        ...
    @data_.setter
    def data_(self, arg1: collections.abc.Sequence[typing.SupportsInt]) -> None:
        ...
    @property
    def height_(self) -> int:
        ...
    @height_.setter
    def height_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def is_bigendian_(self) -> int:
        ...
    @is_bigendian_.setter
    def is_bigendian_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def step_(self) -> int:
        ...
    @step_.setter
    def step_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def width_(self) -> int:
        ...
    @width_.setter
    def width_(self, arg1: typing.SupportsInt) -> None:
        ...
class ImuDataTenAxis_:
    __hash__: typing.ClassVar[None] = None
    imu_basic_: ImuData_
    mag_norm_: ThreeAxis_
    mag_raw_: ThreeAxis_
    pressure_: Pressure_
    def __eq__(self, arg0: ImuDataTenAxis_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, imu_basic_: ImuData_, mag_norm_: ThreeAxis_, mag_raw_: ThreeAxis_, pressure_: Pressure_) -> None:
        ...
    def __ne__(self, arg0: ImuDataTenAxis_) -> bool:
        ...
class ImuData_:
    __hash__: typing.ClassVar[None] = None
    acc_: ThreeAxis_
    gyro_: ThreeAxis_
    sample_timestamp_: SampleTimestamp_
    temp_: SensorTemp_
    tid_: Tid_
    def __eq__(self, arg0: ImuData_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, tid_: Tid_, acc_: ThreeAxis_, gyro_: ThreeAxis_, temp_: SensorTemp_, sample_timestamp_: SampleTimestamp_) -> None:
        ...
    def __ne__(self, arg0: ImuData_) -> bool:
        ...
class JointCmd_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: JointCmd_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, joint_pos_: typing.SupportsFloat, joint_vel_: typing.SupportsFloat, joint_torque_: typing.SupportsFloat, kp_: typing.SupportsFloat, kd_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: JointCmd_) -> bool:
        ...
    @property
    def joint_pos_(self) -> float:
        ...
    @joint_pos_.setter
    def joint_pos_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def joint_torque_(self) -> float:
        ...
    @joint_torque_.setter
    def joint_torque_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def joint_vel_(self) -> float:
        ...
    @joint_vel_.setter
    def joint_vel_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def kd_(self) -> float:
        ...
    @kd_.setter
    def kd_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def kp_(self) -> float:
        ...
    @kp_.setter
    def kp_(self, arg1: typing.SupportsFloat) -> None:
        ...
class JointState_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: JointState_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, model_id_: typing.SupportsInt, motor_id_: typing.SupportsInt, joint_pos_: typing.SupportsFloat, joint_vel_: typing.SupportsFloat, joint_torque_: typing.SupportsFloat, temp_motor_: typing.SupportsInt, temp_mos_: typing.SupportsInt, error_: typing.SupportsInt, joint_error_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: JointState_) -> bool:
        ...
    @property
    def error_(self) -> int:
        ...
    @error_.setter
    def error_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_error_(self) -> int:
        ...
    @joint_error_.setter
    def joint_error_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_pos_(self) -> float:
        ...
    @joint_pos_.setter
    def joint_pos_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def joint_torque_(self) -> float:
        ...
    @joint_torque_.setter
    def joint_torque_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def joint_vel_(self) -> float:
        ...
    @joint_vel_.setter
    def joint_vel_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def model_id_(self) -> int:
        ...
    @model_id_.setter
    def model_id_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def motor_id_(self) -> int:
        ...
    @motor_id_.setter
    def motor_id_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def temp_mos_(self) -> int:
        ...
    @temp_mos_.setter
    def temp_mos_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def temp_motor_(self) -> int:
        ...
    @temp_motor_.setter
    def temp_motor_(self, arg1: typing.SupportsInt) -> None:
        ...
class LegJointCmd_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: LegJointCmd_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt, index_: typing.SupportsInt, cmd_type_: typing.SupportsInt, joint_cmds_: collections.abc.Sequence[JointCmd_]) -> None:
        ...
    def __ne__(self, arg0: LegJointCmd_) -> bool:
        ...
    @property
    def cmd_type_(self) -> int:
        ...
    @cmd_type_.setter
    def cmd_type_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def index_(self) -> int:
        ...
    @index_.setter
    def index_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_cmds_(self) -> list[JointCmd_]:
        ...
    @joint_cmds_.setter
    def joint_cmds_(self, arg1: collections.abc.Sequence[JointCmd_]) -> None:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
class LegJointState_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: LegJointState_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt, index_: typing.SupportsInt, joint_states_: collections.abc.Sequence[JointState_]) -> None:
        ...
    def __ne__(self, arg0: LegJointState_) -> bool:
        ...
    @property
    def index_(self) -> int:
        ...
    @index_.setter
    def index_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_states_(self) -> list[JointState_]:
        ...
    @joint_states_.setter
    def joint_states_(self, arg1: collections.abc.Sequence[JointState_]) -> None:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
class MapMetaData_:
    __hash__: typing.ClassVar[None] = None
    map_load_time_: Time_
    origin_: Pose_
    def __eq__(self, arg0: MapMetaData_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, map_load_time_: Time_, resolution_: typing.SupportsFloat, width_: typing.SupportsInt, height_: typing.SupportsInt, origin_: Pose_) -> None:
        ...
    def __ne__(self, arg0: MapMetaData_) -> bool:
        ...
    @property
    def height_(self) -> int:
        ...
    @height_.setter
    def height_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def resolution_(self) -> float:
        ...
    @resolution_.setter
    def resolution_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def width_(self) -> int:
        ...
    @width_.setter
    def width_(self, arg1: typing.SupportsInt) -> None:
        ...
class NavAll_:
    __hash__: typing.ClassVar[None] = None
    acc_: ThreeAxis_
    euler_: EulerAngle_
    gyro_: ThreeAxis_
    pos_: GnssPos_
    pressure_: Pressure_
    quat_: Quat_
    status_: NavStatus_
    temp_: SensorTemp_
    tid_: Tid_
    utc_: Utc_
    vel_: Vel_
    def __eq__(self, arg0: NavAll_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, tid_: Tid_, acc_: ThreeAxis_, gyro_: ThreeAxis_, euler_: EulerAngle_, quat_: Quat_, temp_: SensorTemp_, pos_: GnssPos_, status_: NavStatus_, vel_: Vel_, utc_: Utc_, pressure_: Pressure_) -> None:
        ...
    def __ne__(self, arg0: NavAll_) -> bool:
        ...
class NavMinUtc_:
    __hash__: typing.ClassVar[None] = None
    nav_basic_: NavMin_
    utc_: Utc_
    def __eq__(self, arg0: NavMinUtc_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, nav_basic_: NavMin_, utc_: Utc_) -> None:
        ...
    def __ne__(self, arg0: NavMinUtc_) -> bool:
        ...
class NavMin_:
    __hash__: typing.ClassVar[None] = None
    euler_: EulerAngle_
    pos_: PosOnly_
    def __eq__(self, arg0: NavMin_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, pos_: PosOnly_, euler_: EulerAngle_) -> None:
        ...
    def __ne__(self, arg0: NavMin_) -> bool:
        ...
class NavStatus_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: NavStatus_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, fusion_status_: typing.SupportsInt, gnss_status_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: NavStatus_) -> bool:
        ...
    @property
    def fusion_status_(self) -> int:
        ...
    @fusion_status_.setter
    def fusion_status_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def gnss_status_(self) -> int:
        ...
    @gnss_status_.setter
    def gnss_status_(self, arg1: typing.SupportsInt) -> None:
        ...
class OccupancyGrid_:
    __hash__: typing.ClassVar[None] = None
    header_: Header_
    info_: MapMetaData_
    def __eq__(self, arg0: OccupancyGrid_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, header_: Header_, info_: MapMetaData_, data_: collections.abc.Sequence[typing.SupportsInt]) -> None:
        ...
    def __ne__(self, arg0: OccupancyGrid_) -> bool:
        ...
    @property
    def data_(self) -> list[int]:
        ...
    @data_.setter
    def data_(self, arg1: collections.abc.Sequence[typing.SupportsInt]) -> None:
        ...
class Point_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Point_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, x_: typing.SupportsFloat, y_: typing.SupportsFloat, z_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: Point_) -> bool:
        ...
    @property
    def x_(self) -> float:
        ...
    @x_.setter
    def x_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def y_(self) -> float:
        ...
    @y_.setter
    def y_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def z_(self) -> float:
        ...
    @z_.setter
    def z_(self, arg1: typing.SupportsFloat) -> None:
        ...
class PosOnly_:
    __hash__: typing.ClassVar[None] = None
    pos_: GnssPos_
    status_: NavStatus_
    tid_: Tid_
    def __eq__(self, arg0: PosOnly_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, tid_: Tid_, pos_: GnssPos_, status_: NavStatus_) -> None:
        ...
    def __ne__(self, arg0: PosOnly_) -> bool:
        ...
class PoseStamped_:
    __hash__: typing.ClassVar[None] = None
    header_: Header_
    pose_: Pose_
    def __eq__(self, arg0: PoseStamped_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, header_: Header_, pose_: Pose_) -> None:
        ...
    def __ne__(self, arg0: PoseStamped_) -> bool:
        ...
class Pose_:
    __hash__: typing.ClassVar[None] = None
    orientation_: Quaternion_
    position_: Point_
    def __eq__(self, arg0: Pose_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, position_: Point_, orientation_: Quaternion_) -> None:
        ...
    def __ne__(self, arg0: Pose_) -> bool:
        ...
class Pressure_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Pressure_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, val_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: Pressure_) -> bool:
        ...
    @property
    def val_(self) -> float:
        ...
    @val_.setter
    def val_(self, arg1: typing.SupportsFloat) -> None:
        ...
class Quat_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Quat_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, q0_: typing.SupportsFloat, q1_: typing.SupportsFloat, q2_: typing.SupportsFloat, q3_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: Quat_) -> bool:
        ...
    @property
    def q0_(self) -> float:
        ...
    @q0_.setter
    def q0_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def q1_(self) -> float:
        ...
    @q1_.setter
    def q1_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def q2_(self) -> float:
        ...
    @q2_.setter
    def q2_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def q3_(self) -> float:
        ...
    @q3_.setter
    def q3_(self, arg1: typing.SupportsFloat) -> None:
        ...
class Quaternion_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Quaternion_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, x_: typing.SupportsFloat, y_: typing.SupportsFloat, z_: typing.SupportsFloat, w_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: Quaternion_) -> bool:
        ...
    @property
    def w_(self) -> float:
        ...
    @w_.setter
    def w_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def x_(self) -> float:
        ...
    @x_.setter
    def x_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def y_(self) -> float:
        ...
    @y_.setter
    def y_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def z_(self) -> float:
        ...
    @z_.setter
    def z_(self, arg1: typing.SupportsFloat) -> None:
        ...
class RemoteControlChange_:
    __hash__: typing.ClassVar[None] = None
    key_: str
    val_: str
    def __eq__(self, arg0: RemoteControlChange_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, key_: str, val_: str) -> None:
        ...
    def __ne__(self, arg0: RemoteControlChange_) -> bool:
        ...
class RemoteControlHead_:
    __hash__: typing.ClassVar[None] = None
    is_absolute_: bool
    def __eq__(self, arg0: RemoteControlHead_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, pos_roll_: typing.SupportsFloat, pos_pitch_: typing.SupportsFloat, is_absolute_: bool) -> None:
        ...
    def __ne__(self, arg0: RemoteControlHead_) -> bool:
        ...
    @property
    def pos_pitch_(self) -> float:
        ...
    @pos_pitch_.setter
    def pos_pitch_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def pos_roll_(self) -> float:
        ...
    @pos_roll_.setter
    def pos_roll_(self, arg1: typing.SupportsFloat) -> None:
        ...
class RemoteControlMotion_:
    __hash__: typing.ClassVar[None] = None
    is_continous_: bool
    token_: str
    def __eq__(self, arg0: RemoteControlMotion_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, token_: str, vx_: typing.SupportsFloat, vy_: typing.SupportsFloat, vyaw_: typing.SupportsFloat, gait_step_: typing.SupportsFloat, is_continous_: bool) -> None:
        ...
    def __ne__(self, arg0: RemoteControlMotion_) -> bool:
        ...
    @property
    def gait_step_(self) -> float:
        ...
    @gait_step_.setter
    def gait_step_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def vx_(self) -> float:
        ...
    @vx_.setter
    def vx_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def vy_(self) -> float:
        ...
    @vy_.setter
    def vy_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def vyaw_(self) -> float:
        ...
    @vyaw_.setter
    def vyaw_(self, arg1: typing.SupportsFloat) -> None:
        ...
class RobotLord_:
    __hash__: typing.ClassVar[None] = None
    acc_: ThreeAxis_
    gyro_: ThreeAxis_
    quat_: Quat_
    tid_: Tid_
    def __eq__(self, arg0: RobotLord_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, tid_: Tid_, acc_: ThreeAxis_, gyro_: ThreeAxis_, quat_: Quat_) -> None:
        ...
    def __ne__(self, arg0: RobotLord_) -> bool:
        ...
class RobotState_:
    __hash__: typing.ClassVar[None] = None
    err_info_: str
    header_: ZVHeader_
    def __eq__(self, arg0: RobotState_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, header_: ZVHeader_, robot_state_: typing.SupportsInt, err_info_: str) -> None:
        ...
    def __ne__(self, arg0: RobotState_) -> bool:
        ...
    @property
    def robot_state_(self) -> int:
        ...
    @robot_state_.setter
    def robot_state_(self, arg1: typing.SupportsInt) -> None:
        ...
class SampleTimestamp_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: SampleTimestamp_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: SampleTimestamp_) -> bool:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
class SensorTemp_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: SensorTemp_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, temp_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: SensorTemp_) -> bool:
        ...
    @property
    def temp_(self) -> float:
        ...
    @temp_.setter
    def temp_(self, arg1: typing.SupportsFloat) -> None:
        ...
class SpeakStatus_:
    __hash__: typing.ClassVar[None] = None
    current_text_: str
    def __eq__(self, arg0: SpeakStatus_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, status_: typing.SupportsInt, current_text_: str, queue_size_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: SpeakStatus_) -> bool:
        ...
    @property
    def queue_size_(self) -> int:
        ...
    @queue_size_.setter
    def queue_size_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def status_(self) -> int:
        ...
    @status_.setter
    def status_(self, arg1: typing.SupportsInt) -> None:
        ...
class String_:
    __hash__: typing.ClassVar[None] = None
    data_: str
    def __eq__(self, arg0: String_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, data_: str) -> None:
        ...
    def __ne__(self, arg0: String_) -> bool:
        ...
class ThreeAxis_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: ThreeAxis_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, x_: typing.SupportsFloat, y_: typing.SupportsFloat, z_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: ThreeAxis_) -> bool:
        ...
    @property
    def x_(self) -> float:
        ...
    @x_.setter
    def x_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def y_(self) -> float:
        ...
    @y_.setter
    def y_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def z_(self) -> float:
        ...
    @z_.setter
    def z_(self, arg1: typing.SupportsFloat) -> None:
        ...
class Tid_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Tid_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, tid_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: Tid_) -> bool:
        ...
    @property
    def tid_(self) -> int:
        ...
    @tid_.setter
    def tid_(self, arg1: typing.SupportsInt) -> None:
        ...
class Time_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Time_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, sec_: typing.SupportsInt, nanosec_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: Time_) -> bool:
        ...
    @property
    def nanosec_(self) -> int:
        ...
    @nanosec_.setter
    def nanosec_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def sec_(self) -> int:
        ...
    @sec_.setter
    def sec_(self, arg1: typing.SupportsInt) -> None:
        ...
class Utc_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Utc_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, year_: typing.SupportsInt, month_: typing.SupportsInt, day_: typing.SupportsInt, hour_: typing.SupportsInt, min_: typing.SupportsInt, sec_: typing.SupportsInt, ms_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: Utc_) -> bool:
        ...
    @property
    def day_(self) -> int:
        ...
    @day_.setter
    def day_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def hour_(self) -> int:
        ...
    @hour_.setter
    def hour_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def min_(self) -> int:
        ...
    @min_.setter
    def min_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def month_(self) -> int:
        ...
    @month_.setter
    def month_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def ms_(self) -> int:
        ...
    @ms_.setter
    def ms_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def sec_(self) -> int:
        ...
    @sec_.setter
    def sec_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def year_(self) -> int:
        ...
    @year_.setter
    def year_(self, arg1: typing.SupportsInt) -> None:
        ...
class Vector3_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Vector3_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, x_: typing.SupportsFloat, y_: typing.SupportsFloat, z_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: Vector3_) -> bool:
        ...
    @property
    def x_(self) -> float:
        ...
    @x_.setter
    def x_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def y_(self) -> float:
        ...
    @y_.setter
    def y_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def z_(self) -> float:
        ...
    @z_.setter
    def z_(self, arg1: typing.SupportsFloat) -> None:
        ...
class Vel_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: Vel_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, vel_e_: typing.SupportsFloat, vel_n_: typing.SupportsFloat, vel_u_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: Vel_) -> bool:
        ...
    @property
    def vel_e_(self) -> float:
        ...
    @vel_e_.setter
    def vel_e_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def vel_n_(self) -> float:
        ...
    @vel_n_.setter
    def vel_n_(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def vel_u_(self) -> float:
        ...
    @vel_u_.setter
    def vel_u_(self, arg1: typing.SupportsFloat) -> None:
        ...
class VoiceText_:
    __hash__: typing.ClassVar[None] = None
    text_: str
    def __eq__(self, arg0: VoiceText_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, text_: str, priority_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: VoiceText_) -> bool:
        ...
    @property
    def priority_(self) -> int:
        ...
    @priority_.setter
    def priority_(self, arg1: typing.SupportsInt) -> None:
        ...
class WaistControl_:
    __hash__: typing.ClassVar[None] = None
    header_: ZVHeader_
    def __eq__(self, arg0: WaistControl_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, header_: ZVHeader_, change_motion_state_: typing.SupportsInt, motion_type_: typing.SupportsInt, target_: collections.abc.Sequence[typing.SupportsFloat], velocity_: typing.SupportsFloat) -> None:
        ...
    def __ne__(self, arg0: WaistControl_) -> bool:
        ...
    @property
    def change_motion_state_(self) -> int:
        ...
    @change_motion_state_.setter
    def change_motion_state_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def motion_type_(self) -> int:
        ...
    @motion_type_.setter
    def motion_type_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def target_(self) -> list[float]:
        ...
    @target_.setter
    def target_(self, arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
    @property
    def velocity_(self) -> float:
        ...
    @velocity_.setter
    def velocity_(self, arg1: typing.SupportsFloat) -> None:
        ...
class WaistJointCmd_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: WaistJointCmd_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt, index_: typing.SupportsInt, cmd_type_: typing.SupportsInt, joint_cmds_: collections.abc.Sequence[JointCmd_]) -> None:
        ...
    def __ne__(self, arg0: WaistJointCmd_) -> bool:
        ...
    @property
    def cmd_type_(self) -> int:
        ...
    @cmd_type_.setter
    def cmd_type_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def index_(self) -> int:
        ...
    @index_.setter
    def index_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_cmds_(self) -> list[JointCmd_]:
        ...
    @joint_cmds_.setter
    def joint_cmds_(self, arg1: collections.abc.Sequence[JointCmd_]) -> None:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
class WaistJointState_:
    __hash__: typing.ClassVar[None] = None
    def __eq__(self, arg0: WaistJointState_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, timestamp_: typing.SupportsInt, index_: typing.SupportsInt, joint_states_: collections.abc.Sequence[JointState_]) -> None:
        ...
    def __ne__(self, arg0: WaistJointState_) -> bool:
        ...
    @property
    def index_(self) -> int:
        ...
    @index_.setter
    def index_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joint_states_(self) -> list[JointState_]:
        ...
    @joint_states_.setter
    def joint_states_(self, arg1: collections.abc.Sequence[JointState_]) -> None:
        ...
    @property
    def timestamp_(self) -> int:
        ...
    @timestamp_.setter
    def timestamp_(self, arg1: typing.SupportsInt) -> None:
        ...
class WaistState_:
    __hash__: typing.ClassVar[None] = None
    euler_: Vector3_
    pose_: Pose_
    def __eq__(self, arg0: WaistState_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, pose_: Pose_, euler_: Vector3_, joints_: collections.abc.Sequence[typing.SupportsFloat], dof_: typing.SupportsInt, curr_motion_state_: typing.SupportsInt) -> None:
        ...
    def __ne__(self, arg0: WaistState_) -> bool:
        ...
    @property
    def curr_motion_state_(self) -> int:
        ...
    @curr_motion_state_.setter
    def curr_motion_state_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def dof_(self) -> int:
        ...
    @dof_.setter
    def dof_(self, arg1: typing.SupportsInt) -> None:
        ...
    @property
    def joints_(self) -> list[float]:
        ...
    @joints_.setter
    def joints_(self, arg1: collections.abc.Sequence[typing.SupportsFloat]) -> None:
        ...
class ZVHeader_:
    __hash__: typing.ClassVar[None] = None
    reserve_: str
    time_: Time_
    trace_id_: str
    def __eq__(self, arg0: ZVHeader_) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, time_: Time_, trace_id_: str, reserve_: str) -> None:
        ...
    def __ne__(self, arg0: ZVHeader_) -> bool:
        ...
__version__: str = '1.0.0'
