/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: JointState_.idl
  Source: JointState_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_JOINTSTATE__HPP
#define DDSCXX_JOINTSTATE__HPP

#include <cstdint>

namespace robot_msgs
{
namespace msg
{
namespace dds_
{
class JointState_
{
private:
 double joint_pos__ = 0.0;
 double joint_vel__ = 0.0;
 double joint_torque__ = 0.0;
 int32_t temp_motor__ = 0;
 int32_t temp_mos__ = 0;
 int32_t error__ = 0;

public:
  JointState_() = default;

  explicit JointState_(
    double joint_pos_,
    double joint_vel_,
    double joint_torque_,
    int32_t temp_motor_,
    int32_t temp_mos_,
    int32_t error_) :
    joint_pos__(joint_pos_),
    joint_vel__(joint_vel_),
    joint_torque__(joint_torque_),
    temp_motor__(temp_motor_),
    temp_mos__(temp_mos_),
    error__(error_) { }

  double joint_pos_() const { return this->joint_pos__; }
  double& joint_pos_() { return this->joint_pos__; }
  void joint_pos_(double _val_) { this->joint_pos__ = _val_; }
  double joint_vel_() const { return this->joint_vel__; }
  double& joint_vel_() { return this->joint_vel__; }
  void joint_vel_(double _val_) { this->joint_vel__ = _val_; }
  double joint_torque_() const { return this->joint_torque__; }
  double& joint_torque_() { return this->joint_torque__; }
  void joint_torque_(double _val_) { this->joint_torque__ = _val_; }
  int32_t temp_motor_() const { return this->temp_motor__; }
  int32_t& temp_motor_() { return this->temp_motor__; }
  void temp_motor_(int32_t _val_) { this->temp_motor__ = _val_; }
  int32_t temp_mos_() const { return this->temp_mos__; }
  int32_t& temp_mos_() { return this->temp_mos__; }
  void temp_mos_(int32_t _val_) { this->temp_mos__ = _val_; }
  int32_t error_() const { return this->error__; }
  int32_t& error_() { return this->error__; }
  void error_(int32_t _val_) { this->error__ = _val_; }

  bool operator==(const JointState_& _other) const
  {
    (void) _other;
    return joint_pos__ == _other.joint_pos__ &&
      joint_vel__ == _other.joint_vel__ &&
      joint_torque__ == _other.joint_torque__ &&
      temp_motor__ == _other.temp_motor__ &&
      temp_mos__ == _other.temp_mos__ &&
      error__ == _other.error__;
  }

  bool operator!=(const JointState_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::robot_msgs::msg::dds_::JointState_>::getTypeName()
{
  return "robot_msgs::msg::dds_::JointState_";
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::JointState_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::JointState_>::type_map_blob_sz() { return 454; }
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::JointState_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::JointState_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x8b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x01,  0xe5,  0x90,  0xfe,  0xf0,  0xbb,  0x1d, 
 0xc3,  0xe6,  0x6e,  0xfa,  0x3d,  0x1e,  0x43,  0x00,  0x73,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x63,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x06,  0x1b,  0x26,  0xf8,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0xfd,  0xf3,  0x1d,  0x75,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0x65,  0x3f,  0x72,  0x49,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x5f,  0x89,  0xe7,  0xa2,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0xcb,  0xcb,  0xd9,  0x1d,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x13,  0x4e,  0x90,  0xda,  0x00, 
 0x09,  0x01,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x41,  0x53,  0x7c,  0xa3,  0x67,  0xca,  0x3b, 
 0x3c,  0xcd,  0x19,  0x7a,  0xb2,  0x25,  0x7f,  0x00,  0xf1,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x2b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x23,  0x00,  0x00,  0x00,  0x72,  0x6f,  0x62,  0x6f, 
 0x74,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73, 
 0x5f,  0x3a,  0x3a,  0x4a,  0x6f,  0x69,  0x6e,  0x74,  0x53,  0x74,  0x61,  0x74,  0x65,  0x5f,  0x00,  0x00, 
 0xb9,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x0a,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x70,  0x6f, 
 0x73,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x0a,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x76,  0x65, 
 0x6c,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x0a,  0x00,  0x0e,  0x00,  0x00,  0x00,  0x6a,  0x6f,  0x69,  0x6e,  0x74,  0x5f,  0x74,  0x6f, 
 0x72,  0x71,  0x75,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x1a,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x04,  0x00,  0x0c,  0x00,  0x00,  0x00,  0x74,  0x65,  0x6d,  0x70,  0x5f,  0x6d,  0x6f,  0x74, 
 0x6f,  0x72,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x04,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x74,  0x65,  0x6d,  0x70,  0x5f,  0x6d,  0x6f,  0x73, 
 0x5f,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x00, 
 0x07,  0x00,  0x00,  0x00,  0x65,  0x72,  0x72,  0x6f,  0x72,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x41,  0x53,  0x7c,  0xa3,  0x67,  0xca,  0x3b, 
 0x3c,  0xcd,  0x19,  0x7a,  0xb2,  0x25,  0x7f,  0xf1,  0x01,  0xe5,  0x90,  0xfe,  0xf0,  0xbb,  0x1d,  0xc3, 
 0xe6,  0x6e,  0xfa,  0x3d,  0x1e,  0x43, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::JointState_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x01,  0xe5,  0x90,  0xfe,  0xf0,  0xbb,  0x1d,  0xc3,  0xe6,  0x6e,  0xfa, 
 0x3d,  0x1e,  0x43,  0x00,  0x77,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x41,  0x53,  0x7c,  0xa3,  0x67,  0xca,  0x3b,  0x3c,  0xcd,  0x19,  0x7a, 
 0xb2,  0x25,  0x7f,  0x00,  0xf5,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::robot_msgs::msg::dds_::JointState_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::robot_msgs::msg::dds_::JointState_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::robot_msgs::msg::dds_::JointState_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::robot_msgs::msg::dds_::JointState_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::robot_msgs::msg::dds_::JointState_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.joint_pos_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.joint_vel_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.joint_torque_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.temp_motor_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.temp_mos_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.error_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::robot_msgs::msg::dds_::JointState_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::JointState_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::robot_msgs::msg::dds_::JointState_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.joint_pos_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.joint_vel_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.joint_torque_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.temp_motor_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.temp_mos_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.error_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::robot_msgs::msg::dds_::JointState_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::JointState_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::robot_msgs::msg::dds_::JointState_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.joint_pos_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.joint_vel_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.joint_torque_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.temp_motor_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.temp_mos_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.error_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::robot_msgs::msg::dds_::JointState_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::JointState_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::robot_msgs::msg::dds_::JointState_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.joint_pos_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.joint_vel_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.joint_torque_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.temp_motor_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.temp_mos_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.error_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::robot_msgs::msg::dds_::JointState_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::JointState_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_JOINTSTATE__HPP
