/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: RemoteControlMotion_.idl
  Source: RemoteControlMotion_.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_REMOTECONTROLMOTION__HPP
#define DDSCXX_REMOTECONTROLMOTION__HPP


namespace robot_msgs
{
namespace msg
{
namespace dds_
{
class RemoteControlMotion_
{
private:
 float vx__ = 0.0f;
 float vy__ = 0.0f;
 float vyaw__ = 0.0f;
 float gait_step__ = 0.0f;
 bool is_continous__ = false;

public:
  RemoteControlMotion_() = default;

  explicit RemoteControlMotion_(
    float vx_,
    float vy_,
    float vyaw_,
    float gait_step_,
    bool is_continous_) :
    vx__(vx_),
    vy__(vy_),
    vyaw__(vyaw_),
    gait_step__(gait_step_),
    is_continous__(is_continous_) { }

  float vx_() const { return this->vx__; }
  float& vx_() { return this->vx__; }
  void vx_(float _val_) { this->vx__ = _val_; }
  float vy_() const { return this->vy__; }
  float& vy_() { return this->vy__; }
  void vy_(float _val_) { this->vy__ = _val_; }
  float vyaw_() const { return this->vyaw__; }
  float& vyaw_() { return this->vyaw__; }
  void vyaw_(float _val_) { this->vyaw__ = _val_; }
  float gait_step_() const { return this->gait_step__; }
  float& gait_step_() { return this->gait_step__; }
  void gait_step_(float _val_) { this->gait_step__ = _val_; }
  bool is_continous_() const { return this->is_continous__; }
  bool& is_continous_() { return this->is_continous__; }
  void is_continous_(bool _val_) { this->is_continous__ = _val_; }

  bool operator==(const RemoteControlMotion_& _other) const
  {
    (void) _other;
    return vx__ == _other.vx__ &&
      vy__ == _other.vy__ &&
      vyaw__ == _other.vyaw__ &&
      gait_step__ == _other.gait_step__ &&
      is_continous__ == _other.is_continous__;
  }

  bool operator!=(const RemoteControlMotion_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::robot_msgs::msg::dds_::RemoteControlMotion_>::getTypeName()
{
  return "robot_msgs::msg::dds_::RemoteControlMotion_";
}

template <> constexpr bool TopicTraits<::robot_msgs::msg::dds_::RemoteControlMotion_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::RemoteControlMotion_>::type_map_blob_sz() { return 398; }
template<> constexpr unsigned int TopicTraits<::robot_msgs::msg::dds_::RemoteControlMotion_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::RemoteControlMotion_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x7b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x24,  0xbc,  0xf1,  0x9a,  0x4a,  0x5c,  0xc2, 
 0xa7,  0xea,  0x2a,  0x37,  0x4c,  0x88,  0xb0,  0x00,  0x63,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x53,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x7b,  0xe8,  0x34,  0x1e,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x4a,  0xcd,  0xf8,  0x82,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x1f,  0x1d,  0x84,  0x25,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x6d,  0x54,  0xa5,  0x97,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x01,  0x8e,  0xc0,  0x98,  0x4a,  0x00, 
 0xe4,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xc6,  0x3a,  0x64,  0x06,  0xa8,  0x35,  0xaa, 
 0xd2,  0x00,  0xb4,  0xac,  0xf8,  0xc1,  0x7e,  0x00,  0xcc,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x34,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x2c,  0x00,  0x00,  0x00,  0x72,  0x6f,  0x62,  0x6f, 
 0x74,  0x5f,  0x6d,  0x73,  0x67,  0x73,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73, 
 0x5f,  0x3a,  0x3a,  0x52,  0x65,  0x6d,  0x6f,  0x74,  0x65,  0x43,  0x6f,  0x6e,  0x74,  0x72,  0x6f,  0x6c, 
 0x4d,  0x6f,  0x74,  0x69,  0x6f,  0x6e,  0x5f,  0x00,  0x8c,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00, 
 0x12,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x76,  0x78,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x12,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x04,  0x00,  0x00,  0x00,  0x76,  0x79,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x76,  0x79,  0x61,  0x77,  0x5f,  0x00,  0x00,  0x00,  0x19,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x67,  0x61,  0x69,  0x74,  0x5f,  0x73,  0x74,  0x65, 
 0x70,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x01,  0x00,  0x0e,  0x00,  0x00,  0x00,  0x69,  0x73,  0x5f,  0x63,  0x6f,  0x6e,  0x74,  0x69, 
 0x6e,  0x6f,  0x75,  0x73,  0x5f,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0xf2,  0xc6,  0x3a,  0x64,  0x06,  0xa8,  0x35,  0xaa,  0xd2,  0x00,  0xb4,  0xac,  0xf8,  0xc1,  0x7e,  0xf1, 
 0x24,  0xbc,  0xf1,  0x9a,  0x4a,  0x5c,  0xc2,  0xa7,  0xea,  0x2a,  0x37,  0x4c,  0x88,  0xb0, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::robot_msgs::msg::dds_::RemoteControlMotion_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x24,  0xbc,  0xf1,  0x9a,  0x4a,  0x5c,  0xc2,  0xa7,  0xea,  0x2a,  0x37, 
 0x4c,  0x88,  0xb0,  0x00,  0x67,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xc6,  0x3a,  0x64,  0x06,  0xa8,  0x35,  0xaa,  0xd2,  0x00,  0xb4,  0xac, 
 0xf8,  0xc1,  0x7e,  0x00,  0xd0,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::robot_msgs::msg::dds_::RemoteControlMotion_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::robot_msgs::msg::dds_::RemoteControlMotion_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::robot_msgs::msg::dds_::RemoteControlMotion_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::robot_msgs::msg::dds_::RemoteControlMotion_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::robot_msgs::msg::dds_::RemoteControlMotion_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.vx_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.vy_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.vyaw_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.gait_step_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.is_continous_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::robot_msgs::msg::dds_::RemoteControlMotion_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::RemoteControlMotion_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::robot_msgs::msg::dds_::RemoteControlMotion_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.vx_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.vy_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.vyaw_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.gait_step_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.is_continous_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::robot_msgs::msg::dds_::RemoteControlMotion_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::RemoteControlMotion_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::robot_msgs::msg::dds_::RemoteControlMotion_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.vx_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.vy_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.vyaw_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.gait_step_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.is_continous_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::robot_msgs::msg::dds_::RemoteControlMotion_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::RemoteControlMotion_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::robot_msgs::msg::dds_::RemoteControlMotion_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.vx_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.vy_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.vyaw_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.gait_step_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.is_continous_()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::robot_msgs::msg::dds_::RemoteControlMotion_& instance, bool as_key) {
  auto &props = get_type_props<::robot_msgs::msg::dds_::RemoteControlMotion_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_REMOTECONTROLMOTION__HPP
