/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: request.idl
  Source: request.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_REQUEST_HPP
#define DDSCXX_REQUEST_HPP

#include <string>

namespace zv_api
{
namespace msg
{
namespace dds_
{
class Request_
{
private:
 std::string request_;

public:
  Request_() = default;

  explicit Request_(
    const std::string& request) :
    request_(request) { }

  const std::string& request() const { return this->request_; }
  std::string& request() { return this->request_; }
  void request(const std::string& _val_) { this->request_ = _val_; }
  void request(std::string&& _val_) { this->request_ = _val_; }

  bool operator==(const Request_& _other) const
  {
    (void) _other;
    return request_ == _other.request_;
  }

  bool operator!=(const Request_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::zv_api::msg::dds_::Request_>::getTypeName()
{
  return "zv_api::msg::dds_::Request_";
}

template <> constexpr bool TopicTraits<::zv_api::msg::dds_::Request_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::zv_api::msg::dds_::Request_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::zv_api::msg::dds_::Request_>::type_map_blob_sz() { return 210; }
template<> constexpr unsigned int TopicTraits<::zv_api::msg::dds_::Request_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::zv_api::msg::dds_::Request_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x3c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x43,  0xea,  0x59,  0x7e,  0x0f,  0xc3,  0x4e, 
 0x5f,  0xad,  0xee,  0x14,  0xe8,  0x68,  0xe9,  0x00,  0x24,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x10,  0x57,  0x3b,  0x87, 
 0x66,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x8b,  0x6b,  0xfd,  0x1e,  0x5a,  0xdc,  0x16, 
 0x39,  0x48,  0xcc,  0x1f,  0x66,  0x6b,  0x72,  0x00,  0x4e,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x24,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x7a,  0x76,  0x5f,  0x61, 
 0x70,  0x69,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x52, 
 0x65,  0x71,  0x75,  0x65,  0x73,  0x74,  0x5f,  0x00,  0x1e,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x16,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x08,  0x00,  0x00,  0x00, 
 0x72,  0x65,  0x71,  0x75,  0x65,  0x73,  0x74,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0xf2,  0x8b,  0x6b,  0xfd,  0x1e,  0x5a,  0xdc,  0x16,  0x39,  0x48,  0xcc,  0x1f, 
 0x66,  0x6b,  0x72,  0xf1,  0x43,  0xea,  0x59,  0x7e,  0x0f,  0xc3,  0x4e,  0x5f,  0xad,  0xee,  0x14,  0xe8, 
 0x68,  0xe9, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::zv_api::msg::dds_::Request_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x43,  0xea,  0x59,  0x7e,  0x0f,  0xc3,  0x4e,  0x5f,  0xad,  0xee,  0x14, 
 0xe8,  0x68,  0xe9,  0x00,  0x28,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x8b,  0x6b,  0xfd,  0x1e,  0x5a,  0xdc,  0x16,  0x39,  0x48,  0xcc,  0x1f, 
 0x66,  0x6b,  0x72,  0x00,  0x52,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::zv_api::msg::dds_::Request_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::zv_api::msg::dds_::Request_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::zv_api::msg::dds_::Request_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::zv_api::msg::dds_::Request_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::zv_api::msg::dds_::Request_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.request(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::zv_api::msg::dds_::Request_& instance, bool as_key) {
  auto &props = get_type_props<::zv_api::msg::dds_::Request_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::zv_api::msg::dds_::Request_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.request(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::zv_api::msg::dds_::Request_& instance, bool as_key) {
  auto &props = get_type_props<::zv_api::msg::dds_::Request_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::zv_api::msg::dds_::Request_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.request(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::zv_api::msg::dds_::Request_& instance, bool as_key) {
  auto &props = get_type_props<::zv_api::msg::dds_::Request_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::zv_api::msg::dds_::Request_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.request(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::zv_api::msg::dds_::Request_& instance, bool as_key) {
  auto &props = get_type_props<::zv_api::msg::dds_::Request_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_REQUEST_HPP
