/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: response.idl
  Source: response.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_RESPONSE_HPP
#define DDSCXX_RESPONSE_HPP

#include <string>

namespace zv_api
{
namespace msg
{
namespace dds_
{
class Response_
{
private:
 std::string response_;

public:
  Response_() = default;

  explicit Response_(
    const std::string& response) :
    response_(response) { }

  const std::string& response() const { return this->response_; }
  std::string& response() { return this->response_; }
  void response(const std::string& _val_) { this->response_ = _val_; }
  void response(std::string&& _val_) { this->response_ = _val_; }

  bool operator==(const Response_& _other) const
  {
    (void) _other;
    return response_ == _other.response_;
  }

  bool operator!=(const Response_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::zv_api::msg::dds_::Response_>::getTypeName()
{
  return "zv_api::msg::dds_::Response_";
}

template <> constexpr bool TopicTraits<::zv_api::msg::dds_::Response_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::zv_api::msg::dds_::Response_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::zv_api::msg::dds_::Response_>::type_map_blob_sz() { return 214; }
template<> constexpr unsigned int TopicTraits<::zv_api::msg::dds_::Response_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::zv_api::msg::dds_::Response_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x3c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x41,  0x6e,  0xf5,  0x1e,  0xe3,  0x0e,  0xd5, 
 0x35,  0x89,  0xcf,  0xd8,  0x50,  0xf0,  0xda,  0x00,  0x24,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0xd1,  0xfc,  0x8e,  0xaf, 
 0x6b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x9c,  0x6f,  0x4b,  0xf9,  0x16,  0xfa,  0x5e, 
 0x03,  0x62,  0x4d,  0x84,  0xce,  0x1a,  0x25,  0x00,  0x53,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x25,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00,  0x7a,  0x76,  0x5f,  0x61, 
 0x70,  0x69,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x52, 
 0x65,  0x73,  0x70,  0x6f,  0x6e,  0x73,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x1f,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00, 
 0x09,  0x00,  0x00,  0x00,  0x72,  0x65,  0x73,  0x70,  0x6f,  0x6e,  0x73,  0x65,  0x00,  0x00,  0x00,  0x00, 
 0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x9c,  0x6f,  0x4b,  0xf9,  0x16,  0xfa,  0x5e, 
 0x03,  0x62,  0x4d,  0x84,  0xce,  0x1a,  0x25,  0xf1,  0x41,  0x6e,  0xf5,  0x1e,  0xe3,  0x0e,  0xd5,  0x35, 
 0x89,  0xcf,  0xd8,  0x50,  0xf0,  0xda, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::zv_api::msg::dds_::Response_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x41,  0x6e,  0xf5,  0x1e,  0xe3,  0x0e,  0xd5,  0x35,  0x89,  0xcf,  0xd8, 
 0x50,  0xf0,  0xda,  0x00,  0x28,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x9c,  0x6f,  0x4b,  0xf9,  0x16,  0xfa,  0x5e,  0x03,  0x62,  0x4d,  0x84, 
 0xce,  0x1a,  0x25,  0x00,  0x57,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::zv_api::msg::dds_::Response_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::zv_api::msg::dds_::Response_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::zv_api::msg::dds_::Response_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::zv_api::msg::dds_::Response_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::zv_api::msg::dds_::Response_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.response(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::zv_api::msg::dds_::Response_& instance, bool as_key) {
  auto &props = get_type_props<::zv_api::msg::dds_::Response_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::zv_api::msg::dds_::Response_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.response(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::zv_api::msg::dds_::Response_& instance, bool as_key) {
  auto &props = get_type_props<::zv_api::msg::dds_::Response_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::zv_api::msg::dds_::Response_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.response(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::zv_api::msg::dds_::Response_& instance, bool as_key) {
  auto &props = get_type_props<::zv_api::msg::dds_::Response_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::zv_api::msg::dds_::Response_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.response(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::zv_api::msg::dds_::Response_& instance, bool as_key) {
  auto &props = get_type_props<::zv_api::msg::dds_::Response_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_RESPONSE_HPP
